### PR TITLE
add support for subgraphs.

### PR DESCRIPTION
**Pull request by zheng-da**
This PR allows users to provide a subgraph as the input of an operator and save and load a graph with subgraph nodes. The subgraph has to be disjoint with the main graph.

### CODE REVIEW

**Comment by zheng-da** [comment]
I tried all unit tests in tests/python/unittest and all of them work fine.

**Comment by tqchen** [comment]
await approval from @piiswrong we want to merge this in so it won't block @zheng-da

**Comment by junrushao1994** [comment]
@tqchen It seems that CI failed because "no space left on device". Could you help with this issue? Thanks!

**Comment by tqchen** [comment]
should be fixed, please rebase to trigger build again

**Pull request merged**
