### PR TITLE
Use skip from pytest instead of nose.

### PR DESCRIPTION
**Pull request by u99127**
Instead of using notest from nose migrate to using skip from pytest.
Replace the check by looking for an exception where if building
with llvm older than 8.0 and skipping the test accordingly.

Ok ?

Ramana

### CODE REVIEW

**Comment by u99127** [comment]
@tqchen , @mshawcroft  - if you could review that would be good.

**Comment by u99127** [comment]
Ok, the CI has broken because on my laptop I have llvm-4 and CI is running with llvm-8 , assuming install_cpu.sh is correct in setting the version of llvm to llvm-8.

Using floordiv instead of div where it suggests is something that moves things forward .I don't understand enough of vnni to look to even fix this up and neither do I have access to the cascadelake hardware to check that this works fine. Neither do I know that CI is running on the appropriate hardware.

In general the testing infrastructure needs to now start adding run time checks for the presence of newer instructions and fail gracefully. I'll note this is also applicable for some of the new AArch64 dot product instructions going in.

I guess for now we either need to xfail this test or skip it entirely, unless the original contributor comes back or someone else can pick this up. 

regards
Ramana

**Comment by anijain2305** [comment]
I will try to take a stab at this next week. I am starting to look into VNNI and I have just gotten hold of a Cascade Lake machine. I will try to find out a way to skip the test by finding a suitable guard condition (LLVM intrinsic or LLVM flag etc).

**Comment by u99127** [comment]
Thanks @anijain2305 , I'll let you handle it.

**Comment by tqchen** [comment]
opened an issue to track the cpu feature detection problem https://github.com/dmlc/tvm/issues/4120

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/4121 provides a temporary replacement of nose skip via pytest skip. needs to followup with a feature detection code , thanks @u99127 @anijain2305 , close this thread for now

**Pull request closed without merging**
