### PR TITLE
Add the acc16 intrinsic support

### PR DESCRIPTION
**Pull request by llyfacebook**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by tqchen** [comment]
@llyfacebook thanks for the contribution, please request reviewers

**Comment by llyfacebook** [comment]
cc @anijain2305

**Comment by tqchen** [comment]
@antinucleon @yzhliu @grwlf  can you help review this PR?

**Comment by llyfacebook** [comment]
I could confirm the CI error is irrelevant.

**Comment by tqchen** [comment]
Please add ASF Header to the file as per CI report

**Comment by tqchen** [comment]
Thanks, @anijain2305 @llyfacebook , this is now merged

**Pull request merged**
