### PR TITLE
[Test] enable NHWC of `relay.testing.mobilenet`

### PR DESCRIPTION
**Pull request by jackwish**
This is part of https://github.com/dmlc/tvm/pull/3859 which enables NHWC for conv2d on ARM devices. Putting it here will be clearer. Please help to review @tqchen @eqy .

EDIT: the force-push fixed lint.

### CODE REVIEW

**Comment by tmoreau89** [comment]
Should we also consider adding a unit test that would check that `relay.testing.mobilenet.get_workload` works with both `layout=NHWC` and `layout=NCHW`?

**Comment by jackwish** [comment]
Hi @tmoreau89 , thank you for the quick review!

> Should we also consider adding a unit test that would check that `relay.testing.mobilenet.get_workload` works with both `layout=NHWC` and `layout=NCHW`?

Yes, adding a test is good point, I have also evaluated before open this PR. To me, testing `relay.testing` is sort like a system integrated test which needs to verify end to end running result, leading to `tests/python/relay/benchmarking`. Sadly, the building (`tvm`) and running (`vm`) with mobilenet NHWC layout is too slow (several minutes) for some reason (maybe because we are initializing NHWC support in TOPI). I think that is not acceptable as NCHW can finish in several seconds. So, I didn't include that part in this PR. And, running `get_workload` without building and running seems test too little... What's your thoughts/suggestions?

**Comment by tmoreau89** [comment]
Good points @jackwish ! It's weird that compiling NHWC is too slow indeed; perhaps it's worth looking into it. Can we at least have a test for `NCHW` and add `NHWC` as a TODO with a linked issue? I'm happy to look into why perf is so slow.

**Comment by jackwish** [comment]
> Good points @jackwish ! It's weird that compiling NHWC is too slow indeed; perhaps it's worth looking into it. Can we at least have a test for `NCHW` and add `NHWC` as a TODO with a linked issue? I'm happy to look into why perf is so slow.

Marking it is a good idea rather than leaving it there :) I will update the PR. I think the building performance is related with the OP schedules - There is not dedicated NHWC schedules for x86 target.

**Comment by tmoreau89** [comment]
Exactly! I think that if this PR gets merged first, I can just enable the test once performance is reasonable.

**Comment by jackwish** [comment]
> Exactly! I think that if this PR gets merged first, I can just enable the test once performance is reasonable.

Thank you @tmoreau89 

@vinx13 @zhiics @icemelon9 , would you please also take a look at this if it can merge now?

**Comment by tmoreau89** [comment]
Looks great, thanks for adding the test. Regarding the CI error I haven't encountered this bug before... Did re-triggering with a minimal commit work around it?

**Comment by zhiics** [comment]
As for CI I cannot log in to retrigger as well, we can probably just submit an empty commit to run it again.

git commit --allow-empty -m "retrigger ci"

**Comment by zhiics** [comment]
NVM, please just ignore my comment. I just saw you updated.

**Comment by jackwish** [comment]
> NVM, please just ignore my comment. I just saw you updated.

Yes, thank you @zhiics

**Pull request merged**
