### PR TITLE
Improve the x86 auto-tune tutorial

### PR DESCRIPTION
**Pull request by peterjc123**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

Previously, `data` was directly used as an input name for the graph. For new users, they may be confused since `data` also sounds like a constant property name. This PR tries to extract it out and make a variable so that it will be clear for the user if they want to auto-tune their own graph.

### CODE REVIEW

**Comment by peterjc123** [comment]
@yzhliu @tqchen @FrozenGene @shoubhik @rankyung

**Comment by peterjc123** [comment]
Related issue: https://discuss.tvm.ai/t/tuningonnx-model-encounter-a-error-num-states-states-list-0-3-size-indexerror-list-index-out-of-range/2952.

**Comment by peterjc123** [comment]
I rebased the PR, but it still can't pass CI. After reading the log, I don't think this PR has anything to do with that build error.

**Comment by kevinthesun** [comment]
No space left on device
Looks like an ci issue.

**Comment by yzhliu** [comment]
@tqchen Could you look into that?

**Comment by tqchen** [comment]
The space issue should have been fixed

**Comment by peterjc123** [comment]
This CI build passes this time.

**Comment by kevinthesun** [comment]
Thanks!

**Pull request merged**
