### PR TITLE
Fixed bugs for conv2d

### PR DESCRIPTION
**Pull request by Laurawly**
Solved bugs raised by @zhreshold and https://github.com/dmlc/tvm/issues/1420

### CODE REVIEW

**Comment by tqchen** [comment]
please followhttps://docs.tvm.ai/contribute/code_review.html#ensure-test-coverage to add regression testcase to avoid this from happening again

**Comment by zhreshold** [comment]
Thanks @Laurawly for fixing it. I can confirm it works for my workloads.

However apparently the default kernels are not optimized for intel graphic cards, therefore it's running much slower than cpu with apple blas. I will look into autotvm later.

**Comment by Laurawly** [comment]
Mac intel graphics doesn’t recognize intel sub group shuffling instructions somehow, that’s why you have to call the cuda schedule which is not optimized for intel graphics. @tqchen should we make the intel subgroup shuffle instructions banned when running on intel graphics on Mac?

**Comment by zhreshold** [comment]
Just had a quick conversation with Yida offline, he mentioned there's Intel's extension to OpenCL which adds support of subgrouping, just wondering if you are familiar with that on Mac?

**Pull request merged**
