### PR TITLE
[TOPI] add binary broadacst

### PR DESCRIPTION
**Pull request by sxjscience**
Add binary op with auto-broadcasting. Support add, sub, mul, div, maximum, minimum

@tqchen

### CODE REVIEW

**Comment by yupbank** [comment]
hey... sorry but i'm a bit confused by this piece of code added in this pr

```
elif typ == "div":
        rhs_npy = np.abs(rhs_npy) + 0.001
        out_npy = lhs_npy / rhs_npy
```
why do you need to `abs` right hand side ?

**Comment by sxjscience** [comment]
This ensures that the denominator is not too small/zero. Otherwise the result may be inf or nan.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by yupbank** [comment]
Why would abs ensure not too small ? And isn’t it going to make any positive divide negative results wrong? Since it would flip the negative right hand side into positive right hand side ?

**Comment by sxjscience** [comment]
It’s in the testing code.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by sxjscience** [comment]
You are right. In this case it’s unnecessary since uniform is between 0,1. Adding an abs +eps just makes sure that the result is positive no matter how we initialize the denominator. It also works when data are initialized as normal().

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Pull request merged**
