### PR TITLE
Force code_object_v2 for amd gpu backend

### PR DESCRIPTION
**Pull request by petrex**
Goal : Stick to code_object_v2 for LLVM AMDGPU backend at this moment.

I am taking the action item to enable code_object_v3 when it's ready and validated.

### CODE REVIEW

**Comment by masahi** [comment]
Does v2 work on recent LLVM?

**Comment by petrex** [comment]
code_object_v2 is still supported, although this is not the default. 
See https://llvm.org/docs/AMDGPUUsage.html

A side note: we are sorting out issue w.r.t to code_object_v3. At this moment, code_object_v2 would be a safer choice.

**Comment by t-vi** [comment]
Just to add some note about the impact: This fixes the cross-thread reductions, which were broken because the code v3 objects seem to loose the fixed group segment ("shared memory") property, and reading out of bounds returns 0.

**Comment by petrex** [comment]
yes, this is one of the motivations behind the fix. Thanks for the confirmation.

**Pull request merged**
