### PR TITLE
[ARITH] cleanup the indexmod/div on python side

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by tqchen** [comment]
@kevinthesun @icemelon9 please check the changes in the multi-box prior. The error was detected when performing an integer division that has ambiguity, but seems we should have do float div.

**Comment by kevinthesun** [comment]
> @kevinthesun @icemelon9 please check the changes in the multi-box prior. The error was detected when performing an integer division that has ambiguity, but seems we should have do float div.

@tqchen Do you mean we need to explicitly cast size[i] * height to avoid such error?

**Comment by tqchen** [comment]
just to confirm what is the intend of the code. I changed the code to explicitly cast to float. Otherwise it will do integer division(the result will be rounded)

**Comment by tqchen** [comment]
@kevinthesun to elaborate the further, previously the code was

```python
ratio_int * height / width / 2.0 
```

Originally because both ```ratio_int * height``` and ```width``` have int type, the division will be translated to integer division(which truncates). Imagine ratio_int = 2, height=10, width = 20, the result of ```ratio_int * height / width ``` will be ```2 * 10 / 20 = 1```. 

The current set of change detects this division and raises an error, so we can explicit do the cast which will give the floating pt division.

```python
float32(ratio_int * height) / width
```

I assumed that the floating pt division is what we want here and we just revealed a previous bug in the code. but it would be great if you can also help confirm that also cc @icemelon9

**Pull request merged**
