### PR TITLE
Fix Web Build after CMake transition.

### PR DESCRIPTION
**Pull request by tqchen**
Followup of #2379

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
@tqchen I have to harcode the path still in prepare_tests_libs.py as in #2379 

when I do it I find that I have openGL errors:

```
david@hercules:~/tvm/tests/web$ python prepare_test_libs.py
[18:34:44] /home/david/tvm/src/codegen/llvm/codegen_llvm.cc:75: Set native vector bits to be 128 for asmjs
Traceback (most recent call last):
  File "prepare_test_libs.py", line 21, in <module>
    prepare_test_libs(os.path.join(curr_path, "../../build"))
  File "prepare_test_libs.py", line 17, in prepare_test_libs
    emscripten.create_js(os.path.join(base_path, "test_module.js"), '../../build/libtvm_web_runtime.bc')
  File "/home/david/.local/lib/python2.7/site-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/contrib/emscripten.py", line 64, in create_js
    raise RuntimeError(msg)
RuntimeError: Compilation error:
error: undefined symbol: glfwCreateWindow
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: glfwDestroyWindow
error: undefined symbol: glfwMakeContextCurrent
error: undefined symbol: glfwSetErrorCallback
error: undefined symbol: glfwWindowHint
Error: Aborting compilation due to previous errors
shared:ERROR: '/home/david/emsdk/node/8.9.1_64bit/bin/node /home/david/emsdk/emscripten/1.38.22/src/compiler.js /tmp/tmpaY45Vk.txt /home/david/emsdk/emscripten/1.38.22/src/library_pthread_stub.js' failed (1)

```

I try to install glfw but the issue still remains:

```
sudo apt-get install libglfw3-dev libglfw3
```

**Comment by tqchen** [comment]
This seems has things to do with the emscripten versions, this can be fixed by patching contrib/emscripten.py with flag USE_GLFW=1, but then there seems still are some issues on WASM in the latest emscripten

**Comment by DavidGOrtega** [comment]
@tqchen so... its dead? :grimacing:

**Comment by tqchen** [comment]
it is certainly not dead. To be clear, the code works for an older version of env that I had, but seems has some problem in the latest version when I attempted to revive a docker version.  The main cause seems to due to the major movement from ASMJS to WASM while the lack of vector support in WASM.

I just think we need some developer time to look into it:)

**Comment by tqchen** [comment]
I opened a thread to track it https://github.com/dmlc/tvm/issues/2425

**Pull request merged**
