### PR TITLE
Fixing package path in tflite test

### PR DESCRIPTION
**Pull request by wangshangsam**
Issue [#3425](https://github.com/dmlc/tvm/issues/3425)

### CODE REVIEW

**Comment by wangshangsam** [comment]
@tqchen @kevinthesun Please add reviewers. Thanks!

**Comment by apivovarov** [comment]
Currently TVM docker image uses tensorflow 1.13.1 and it can work fine with `tvm.contrib.lite` module

tensorflow 1.14 was released 6 days ago and it does not have `lite` under `tvm.contrib`

We should also change tensorflow version to 1.14 in tflite schema (both in tests and in tutorial) `ubuntu_install_tflite.sh` and `from_tflite.py`

**Comment by wangshangsam** [comment]
@apivovarov The new commit should suffix for both tf.contrib.lite and tf.lite

**Comment by wangshangsam** [comment]
@apivovarov The new commit should suffice for both tf.contrib.lite and tf.lite

**Comment by tqchen** [comment]
Thanks, @wangshangsam @apivovarov , this PR is now merged

**Pull request merged**
