### PR TITLE
[autotvm] fix #2617

### LINKED ISSUE #2617: AutoTVM x86 Tutorial is broken on MacOS
python tune_relay_x86.py
```
Extract tasks...
Tuning...
[Task  1/12]  Current/Best:    0.00/   0.00 GFLOPS | Progress: (0/400) | 0.00 sTraceback (most recent call last):
  File "tune_relay_x86.py", line 183, in <module>
    tune_and_evaluate(tuning_option)
  File "tune_relay_x86.py", line 157, in tune_and_evaluate
    tune_kernels(tasks, **tuning_opt)
  File "tune_relay_x86.py", line 142, in tune_kernels
    autotvm.callback.log_to_file(log_filename)])
  File "/Users/bingxu/tvm/python/tvm/autotvm/tuner/tuner.py", line 92, in tune
    measure_batch = create_measure_batch(self.task, measure_option)
  File "/Users/bingxu/tvm/python/tvm/autotvm/measure/measure.py", line 236, in create_measure_batch
    attach_objects = runner.set_task(task)
  File "/Users/bingxu/tvm/python/tvm/autotvm/measure/measure_methods.py", line 326, in set_task
    super(LocalRunner, self).set_task(task)
  File "/Users/bingxu/tvm/autotvm/measure/measure_methods.py", line 196, in set_task
    raise RuntimeError("Cannot get remote devices from the tracker. "
RuntimeError: Cannot get remote devices from the tracker. Please check the status of tracker by 'python -m tvm.exec.query_rpc_tracker --port [THE PORT YOU USE]' and make sure you have free devices on the queue status.
```

python -m tvm.exec.query_rpc_tracker --port 9000

```
Tracker address localhost:9000

Server List
----------------------------
server-address	key
----------------------------
::1:50954	server:$local$device$9000
----------------------------

Queue Status
------------------------------------------
key                  total  free  pending
------------------------------------------
$local$device$9000   1      0     1
------------------------------------------
```

### PR DESCRIPTION
**Pull request by antinucleon**
Fix https://github.com/dmlc/tvm/issues/2617

Note: In future we should get avoid using ```localhost``` to avoid similar issue

### CODE REVIEW

**Comment by icemelon9** [comment]
Have you verified that this change won't break on other OS such as Ubuntu? Also why do you use "0.0.0.0" instead of "127.0.0.1"?

**Comment by antinucleon** [comment]
@icemelon9 I also tested on CentOS it works well. I use 0.0.0.0 because in origin codebase ```0.0.0.0``` and ```localhost``` are mixed and there is no ```127.0.0.1```

**Comment by antinucleon** [comment]
> Please also modify `tune_relay_arm.py ` and `tune_relay_mobile_gpu.py` in the tutorial folder

Done

**Comment by eqy** [comment]
Do we also want to update the old nnvm tutorials?

**Comment by antinucleon** [comment]
@eqy I think we should remove all old nnvm tutorials.

**Comment by tqchen** [comment]
I agree we can remove corresponding nnvm tutorial once we have a relay version of it.

**Comment by antinucleon** [comment]
ping @eqy

**Comment by eqy** [comment]
Thanks @antinucleon, this is merged.

**Pull request merged**
