### PR TITLE
[NNPACK] Test NNPACK integration in continuous build.

### PR DESCRIPTION
**Pull request by ajtulloch**
The previous integration ended up bitrotting, so this approach of adding NNPACK in the CI should be helpful. 

The code should be tested by the existing nosestests, but instead of silently skipping the NNPACK tests they should be executed.

This is my first time modifying the Docker/Jenkins aspects of this system, so I'm not really sure if this is the right approach.

### CODE REVIEW

**Comment by ajtulloch** [comment]
@tqchen (and other committers) I believe due to https://support.cloudbees.com/hc/en-us/articles/227246367-Why-Jenkinsfile-changes-Are-Not-Reflected-in-PR-Build this PR won't be tested in CI, so I will need your help in testing/landing this.

From http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-2085/runs/1/log/?start=0:

```
Pull request #2085 opened
Connecting to https://api.github.com using tqchen/****** (tvmci)
Connecting to https://api.github.com to check permissions of obtain list of ajtulloch for dmlc/tvm
Loading trusted files from base branch master at fc83c7f26d825c357ec7369ca06f20fc9ef62d3f rather than a91af61acc8839437469feede7bf8c96d4b96a32
Obtained Jenkinsfile from fc83c7f26d825c357ec7369ca06f20fc9ef62d3f
...
```

**Comment by tqchen** [comment]
Can you remove the jenkinsfile change first and let us bring in docker change in? We choose not to automatically rebuild docker image but manually rebuild it so there won't be too many bad space, this means we need to merge the docker change in first, update the images for the CI, before we start trigger the Jenkins test

**Comment by ajtulloch** [comment]
@tqchen updated, thanks.

**Comment by tqchen** [comment]
to follow up on this, the CI docker image has been updated

**Comment by ajtulloch** [comment]
@tqchen thanks - should I send the Jenkinsfile update now as well?

**Comment by tqchen** [comment]
Yes, please, or if you can point the diff commit to me, I can send it in to trigger it

**Comment by ajtulloch** [comment]
@tqchen https://github.com/dmlc/tvm/pull/2095 is a candidate PR.

**Pull request merged**
