### PR TITLE
[Relay][Frontend] Simplify parameter handling in Tensorflow frontend

### PR DESCRIPTION
**Pull request by alexeyr**
On top of https://github.com/dmlc/tvm/pull/2943.

### CODE REVIEW

**Comment by srkreddy1238** [comment]
@alexeyr can you rebase ?

**Comment by tqchen** [comment]
ping @alexeyr

**Comment by alexeyr** [comment]
@srkreddy1238 @Laurawly @Huyuwei Rebased, please review

**Comment by tqchen** [comment]
ping @srkreddy1238

**Comment by tqchen** [comment]
Thanks, @srkreddy1238 @alexeyr , this PR is now merged

**Pull request merged**
