### PR TITLE
[RELAY][OP] comparison

### PR DESCRIPTION
**Pull request by junrushao1994**
This PR contains the following operators by copy-pasting.

* `equal` (only add docstring)
* `not_equal`
* `greater`
* `greater_equal`
* `less`
* `less_equal`

TODO:
- [x] Check support level
- [x] Add tests
- [x] Find a right filename putting these operators. Is `elemwise.cc` the right place?

Related issue: #1799

### CODE REVIEW

**Comment by junrushao1994** [comment]
@tqchen Can I assume support levels for these 6 operators are all 4?

**Comment by srkreddy1238** [comment]
> * [ ]  Find a right filename putting these operators. Is `elemwise.cc` the right place?

All these support broadcast versions, hence could go to broadcast.cc

**Comment by junrushao1994** [comment]
Testcases are added just now. 2 issues:

1. Could we somehow add `bool` as an alias to `uint1`?
2. Unknown type error is not handled properly #1830

**Comment by junrushao1994** [comment]
Rebased w.r.t the current master.

**Comment by junrushao1994** [comment]
@tqchen @srkreddy1238 Hey folks, could you help review this PR?

**Pull request merged**
