### PR TITLE
[Tensorflow, NNVM, TOPI] Support for logical operators

### PR DESCRIPTION
**Pull request by ashutoshparkhi**
Support for logical OR/AND/NOT 

Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by jroesch** [comment]
Can we expose these in Relay too? doesn't Numpy use different names for these operators? if so we should be consistent.

**Comment by ashutoshparkhi** [comment]
@jroesch Names in numpy seem to be consistent with this commit. I am not much aware of the Relay side. Could you please send some quick pointers to start off?

**Comment by zhiics** [comment]
@ashutoshparkhi Here is a tutorial of adding an operator to Relay: https://docs.tvm.ai/dev/relay_add_op.html Hopefully this helps.

**Comment by tqchen** [comment]
@ashutoshparkhi can you please update on this PR?

**Comment by abergeron** [comment]
I'm up for doing the relay part in a follow-up PR if this is ok to merge for NNVM.

**Comment by tqchen** [comment]
OK, this is merged. @abergeron followup with relay op is more than welcomed

**Comment by ashutoshparkhi** [comment]
Thank you @tqchen  and @abergeron.

**Pull request merged**
