### PR TITLE
[Relay][Frontend] Add a bunch of ops in tf converter

### PR DESCRIPTION
**Pull request by yongwww**
Add several ops in tf converter, fix issue of "Range",  add a few test cases like unpack, op list is as below.
- [x] - Abs 
- [x] - FloorDiv
- [x] - GatherNd
- [x] - LeftShift
- [x] - LogSoftmax
- [x] - Max
- [x] - Min
- [x] - Mod
- [x] - RightShift
- [x] - ZerosLike
- [x] - TruncateMod

cc: @srkreddy1238 @zhiics @wweic @yzhliu

### CODE REVIEW

**Comment by yongwww** [comment]
ping @srkreddy1238 @zhiics

**Comment by zhiics** [comment]
It looks good to me. Please rebase. @srkreddy1238 Can you take a look as well.

**Comment by tqchen** [comment]
@yongwww please check the ci error https://github.com/dmlc/tvm/pull/3270

**Comment by yongwww** [comment]
@tqchen  CI issue was fixed.

**Comment by tqchen** [comment]
Thanks, @yongwww this PR is now merged.

**Pull request merged**
