### PR TITLE
[TVM][LANG] Add eager simplification for operations with FloatImm

### PR DESCRIPTION
**Pull request by icemelon9**
Add eager simplification for operations of add, sub, mul, div, ceil, floor, round, trunc, and cast with float constants.

### CODE REVIEW

**Comment by tqchen** [comment]
Thank you @icemelon9 can you add some test cases as per https://docs.tvm.ai/contribute/code_review.html#ensure-test-coverage

**Comment by icemelon9** [comment]
@tqchen Test case for eager simplification is added.

**Comment by icemelon9** [comment]
Thanks @tqchen for the review.

**Comment by merrymercy** [comment]
This PR introduces a performance regression on resnet-18 on Mali GPUs.
Some loops cannot be vectorized after this PR. I am not sure about the reasons, will investigate later (volunteers are welcomed).

cc @yzhliu @icemelon9

**Comment by yzhliu** [comment]
Rough investigation, regression disappears by applying this patch: https://gist.github.com/yzhliu/0d2cdfc9fa92127b81a1298d5bec55a0

**Comment by icemelon9** [comment]
This may break the arange op because it relies on the simplification on floating expr to calculate the output shape. Maybe the new canonical simplification can handle this instead of eager simplification. Could you test it?

**Pull request merged**
