### PR TITLE
[Fix] Fix the logic of the number of nodes checking in op fusion

### PR DESCRIPTION
**Pull request by yidawang**
move the number of nodes checking in op fusion up to the dom tree level, so that the fusion won't be halted in the middle.

@MarisaKirisame @kevinthesun @zhiics

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@zhiics there is nothing special for tuple. It fail for other cases too - in mergefromto, the groups and functions that will generate is already defined, and it must merge at that point, or stuff will goes out of scope.

**Comment by yidawang** [comment]
@tqchen What kind of test case is in your mind?

**Comment by tqchen** [comment]
would be great if there is a regression test that failed the case before the patch

**Comment by yidawang** [comment]
test case added @tqchen

**Comment by zhiics** [comment]
Thanks everyone. This is now merged.

**Pull request merged**
