### PR TITLE
[CI] Update rust format version

### PR DESCRIPTION
**Pull request by tqchen**
cc @nhynes @ehsanmok 

The update the rust docker creates outrage in the CI because of version mismatch. Next time, we might need to consider a safe transition rule(e.g. remove test or relax version for now)

### CODE REVIEW

**Comment by ehsanmok** [comment]
You are right! Thanks for the update. The docker install rustfmt version must match exactly with the version used in `.rustfmt`.

**Comment by nhynes** [comment]
This is a giant problem with rustfmt. Fortunately we've finally made it to stable nightly (whatever that means) so it'll be quite a while before we update again. At most in 3 years when rust releases another edition.

**Comment by tqchen** [comment]
@nhynes can u comment on http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-2550/3/pipeline?  If there is a quick fix to this problem

**Comment by ehsanmok** [comment]
Hopefully as Nick said, we won't get headache after this. The lesson was such changes should be verified independent from current docker setup then commit the changes all at once in docker and rustfmt config.

**Pull request merged**
