### PR TITLE
[Bugfix] Fix a memory leak in OpManager

### PR DESCRIPTION
**Pull request by hlu1**
Add destructor in OpManager to delete `frontend_funcs`.

Memory leak caught by LeakSanitizer:
```
==2522658==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x48f130 in operator new(unsigned long) (/data/users/hlu/tvm/sparse/tvm_sparse_benchmark.cc+0x48f130)
    #1 0x7efd36d620dd in tvm::relay::$_2::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const tvm/tvm/src/relay/ir/op.cc:152
    #2 0x7efd36d613e8 in std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::relay::$_2>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) third-party-buck/platform007/build/libgcc/include/c++/7.3.0/bits/std_function.h:316
    #3 0x7efd37fa4d08 in std::function<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const third-party-buck/platform007/build/libgcc/include/c++/7.3.0/bits/std_function.h:706
    #4 0x7efd37f9d022 in tvm::runtime::TVMRetValue tvm::runtime::PackedFunc::operator()<char const (&) [4], char const (&) [13], tvm::runtime::TypedPackedFunc<tvm::Schedule (tvm::Attrs const&, tvm::Array<tvm::Tensor, void> const&, tvm::Target const&)>&, int>(char const (&) [4], char const (&) [13], tvm::runtime::TypedPackedFunc<tvm::Schedule (tvm::Attrs const&, tvm::Array<tvm::Tensor, void> const&, tvm::Target const&)>&, int&&) const tvm/tvm/include/tvm/runtime/packed_func.h:1205
    #5 0x7efd37f9acf4 in tvm::registerTopiSchedules()::$_0::operator()() const caffe2/caffe2/fb/tvm/topi/topi_init.cc:53
    #6 0x7efd37f99abc in void std::__invoke_impl<void, tvm::registerTopiSchedules()::$_0>(std::__invoke_other, tvm::registerTopiSchedules()::$_0&&) third-party-buck/platform007/build/libgcc/include/c++/7.3.0/bits/invoke.h:60
    #7 0x7efd37f99a8c in std::__invoke_result<tvm::registerTopiSchedules()::$_0>::type std::__invoke<tvm::registerTopiSchedules()::$_0>(tvm::registerTopiSchedules()::$_0&&) third-party-buck/platform007/build/libgcc/include/c++/7.3.0/bits/invoke.h:95
    #8 0x7efd37f9972c in std::invoke_result<tvm::registerTopiSchedules()::$_0>::type std::invoke<tvm::registerTopiSchedules()::$_0>(tvm::registerTopiSchedules()::$_0&&) third-party-buck/platform007/build/libgcc/include/c++/7.3.0/functional:80
    #9 0x7efd37f9957a in void folly::basic_once_flag<folly::SharedMutexImpl<false, void, std::atomic, false, false>, std::atomic>::call_once_slow<tvm::registerTopiSchedules()::$_0>(tvm::registerTopiSchedules()::$_0&&) buck-out/dev/gen/folly/synchronization/call_once#header-mode-symlink-tree-with-header-map,headers/folly/synchronization/CallOnce.h:110
    #10 0x7efd37f99165 in void folly::basic_once_flag<folly::SharedMutexImpl<false, void, std::atomic, false, false>, std::atomic>::call_once<tvm::registerTopiSchedules()::$_0>(tvm::registerTopiSchedules()::$_0&&) buck-out/dev/gen/folly/synchronization/call_once#header-mode-symlink-tree-with-header-map,headers/folly/synchronization/CallOnce.h:101
    #11 0x7efd37f99165 in void folly::call_once<folly::SharedMutexImpl<false, void, std::atomic, false, false>, std::atomic, tvm::registerTopiSchedules()::$_0>(folly::basic_once_flag<folly::SharedMutexImpl<false, void, std::atomic, false, false>, std::atomic>&, tvm::registerTopiSchedules()::$_0&&) buck-out/dev/gen/folly/synchronization/call_once#header-mode-symlink-tree-with-header-map,headers/folly/synchronization/CallOnce.h:57
    #12 0x7efd37f99165 in tvm::registerTopiSchedules() caffe2/caffe2/fb/tvm/topi/topi_init.cc:26
    #13 0x4369e4 in main tvm/sparse/tvm_sparse_benchmark.cc:125
    #14 0x7efd1c7c81a5 in __libc_start_main /home/engshare/third-party2/glibc/2.26/src/glibc-2.26/csu/libc-start.c:308:16
    #15 0x432ce9 in _start /home/engshare/third-party2/glibc/2.26/src/glibc-2.26/sysdeps/x86_64/start.S:120
```
@tqchen, @jroesch, please review.

### CODE REVIEW

**Comment by antinucleon** [comment]
```
==2869722== 
==2869722== HEAP SUMMARY:
==2869722==     in use at exit: 285,243 bytes in 5,642 blocks
==2869722==   total heap usage: 65,516 allocs, 59,874 frees, 15,923,160 bytes allocated
==2869722== 
==2869722== LEAK SUMMARY:
==2869722==    definitely lost: 32 bytes in 1 blocks
==2869722==    indirectly lost: 1 bytes in 1 blocks
==2869722==      possibly lost: 47,811 bytes in 964 blocks
==2869722==    still reachable: 237,399 bytes in 4,676 blocks
==2869722==                       of which reachable via heuristic:
==2869722==                         stdstring          : 44,616 bytes in 914 blocks
==2869722==         suppressed: 0 bytes in 0 blocks
==2869722== Rerun with --leak-check=full to see details of leaked memory
==2869722== 
==2869722== For counts of detected and suppressed errors, rerun with: -v
==2869722== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by tqchen** [comment]
In this particular case, we intentionally not delete the front_end_funcs in this case. Mainly because sometimes the frontend functions are destructed after the python env already unloaded, and deleting them(calling into ctypes deleter) causes segfault, as in the CI

**Comment by hlu1** [comment]
Sounds good

**Comment by tqchen** [comment]
Thanks @hlu1 for raising the PR, I think we will welcome a PR that adds an additional comment to the code so we see what is going on :)

**Comment by hlu1** [comment]
@tqchen, not deleting the frontend_funcs is the right behavior when the python frontend is used, because the relay frontend_funcs are registered and then deleted by python. However, in pure C++ environment (our case), we have to register those funcs in C++, not deleting them results in a memory leak. What do you think is the most proper way to fix it?

**Comment by tqchen** [comment]
Good point, I think a better way would be pass in an additional flag(when registering global) (frontend_func) to indicate whether it is native c++ or a frontend function and handle them differently.

**Pull request closed without merging**
