### PR TITLE
[QUANTIZE] Memorizing the quantize node mapping

### PR DESCRIPTION
**Pull request by ZihengJiang**
To avoid duplicated simulated quantize.

@tqchen @vinx13 @jwfromm

### CODE REVIEW

**Comment by ZihengJiang** [comment]
Also, let's remove `skip_k_conv` since it can be expressed by `skip_conv_layers`, and remove `use_stop_fusion` since it is mainly for `store_lowbit_output`. @vinx13 @jwfromm

**Comment by tqchen** [comment]
@vinx13  would be great if we can find alternates. Ideally, we want to deal with both cases.

**Comment by ZihengJiang** [comment]
@vinx13 I may not get the point. Does it matter to merge those two i32 cast? The main residual block still will output 8bit (in front of the `stop_fusion`).

**Comment by vinx13** [comment]
@ZihengJiang It will impact the performance. Although Stop_fusion can make sure that conv2d + fused ops produce int8 result, if the int32 casts are merged, it will be put into a separate sub function

**Comment by tqchen** [comment]
@ZihengJiang @vinx13 can you please followup now that #3280  is merged?

**Comment by vinx13** [comment]
@ZihengJiang please rebase against master

**Pull request merged**
