### PR TITLE
[Relay][TopHub] Add switch to disable TopHub download

### PR DESCRIPTION
**Pull request by soiferj**
Add a switch to disable downloading from TopHub. On machines which don't have internet access, failing to download from TopHub slows down `relay.build` significantly.

@merrymercy would you be able to take a look?

### CODE REVIEW

**Comment by tqchen** [comment]
This seems to be a behavior that can be configured by env variable, by specifying the tophub location rather than putting it into a build. We could avoid download when the location is specified to be none

**Comment by soiferj** [comment]
I’m fine with that solution, but it doesn’t seem backward compatible for people who depend on tophub today. Do you know if a lot of people rely on it?

I suppose this could work if we used the default location when the environment variable isn’t set, and if we set it to NONE explicitly then we don’t download. That seems a little strange though.

**Comment by tqchen** [comment]
Let us keep the backward compact by setting the default loc if not set for now.

**Comment by soiferj** [comment]
Updated to read form environment variable `TOPHUB_LOCATION`. If it's set to `NONE`, we will return `EmptyContext`.

**Comment by soiferj** [comment]
@merrymercy @yzhliu would you be able to take a look?

**Comment by merrymercy** [comment]
@soiferj Thanks. It is merged

**Pull request merged**
