### PR TITLE
More fixes and tweaks to the cuda conda packages

### PR DESCRIPTION
**Pull request by abergeron**
This brings some fixes to the conda cuda build so that it works once again.

I've also added support for cudnn in those packages since anaconda started packaging it.

There should really be a phase in the tests that builds the packages.  If there is interest I can make an attempt at adding that to the Jenkinsfile.

### CODE REVIEW

**Comment by abergeron** [comment]
@tqchen

**Comment by tqchen** [comment]
Thanks, @abergeron for the contribution! Yes, a CI script that verifies the build will be nice. One question about the docker env. We normally use https://github.com/dmlc/tvm/tree/master/docker as a way to cache pre-built docker images so we don't have to build again and avoids some problems when there is an upstream change, can we also do that in conda packaging?

**Comment by abergeron** [comment]
It would certainly be possible to adapt my build scripts to generate the GPU docker images and pre-build them.

As for the CPU packages they are currently built as-is, but I could make a docker image for that too.

I can add that to this PR or make a new one.

**Comment by tqchen** [comment]
a new PR would be great since we build and cache the docker images

**Comment by tqchen** [comment]
Thanks, @abergeron , this PR is now merged

**Pull request merged**
