### PR TITLE
[Relay] add python doc for function in ir_pass

### PR DESCRIPTION
**Pull request by MarisaKirisame**
It is almost done - I have no idea what to do with check_kind.
If there is only 1 arg, it is interpreted as type.
If there is only 2 arg, the first is env, and the second is type.
what should I do? redesign the check_kind interface to has env coming last?

### CODE REVIEW

**Comment by slyubomirsky** [comment]
Weird, I thought the env already was the second argument for `check_kind`. Yes, I think it would be totally reasonable to change the interface in that manner, definitely how it should have been done in the first place

**Comment by MarisaKirisame** [comment]
@slyubomirsky it was probably lose in the sea of git branches.
No worry, I got it then.

**Comment by MarisaKirisame** [comment]
It is all good.
@slyubomirsky @joshpoll @masahi can you guys review?

**Comment by slyubomirsky** [comment]
If the tests pass, it looks good to me.

**Comment by MarisaKirisame** [comment]
@tqchen I had addressed the review comment.

**Pull request merged**
