### PR TITLE
Add relay tutorial to make doc

### PR DESCRIPTION
**Pull request by kevinthesun**
@tqchen @Laurawly

### CODE REVIEW

**Comment by tqchen** [comment]
I think a better solution is to move these tutorials into the correct places, in frontend, or the root. Sorry I overlooked it when merging them in.

**Comment by tqchen** [comment]
In particular, all the current tutorials should go into the frontend folder.

**Comment by kevinthesun** [comment]
Do you mean moving all relay tutorials to frontend?

**Comment by tqchen** [comment]
yes to all the tutorials so far

**Pull request closed without merging**
