### PR TITLE
Halide -> HalideIR

### PR DESCRIPTION
**Pull request by abadams**
To make it possible to use Halide and tvm in the same project.

### CODE REVIEW

**Comment by abadams** [comment]
See companion PR at https://github.com/dmlc/HalideIR/pull/15

**Comment by tqchen** [comment]
The HalideIR pr has been merged. can you update submodule and rebase? Thanks

**Comment by abadams** [comment]
Done, I think. Haven't updated submodules in a PR before, so hopefully I didn't screw something up.

**Comment by tqchen** [comment]
thanks!

**Pull request merged**
