### PR TITLE
Expose remove API

### PR DESCRIPTION
**Pull request by abergeron**
This is an alternative to #3433, but can also stand by itself.

I'm pretty sure the C functions and the python path works, but I haven't really tested the other frontends so there definitely might be something wrong in those.

I'm not sure who is best to summon for frontend reviews so if you have an idea feel free to do it for me.

### CODE REVIEW

**Comment by tqchen** [comment]
Thinking more about it. Perhaps we could keep the C API concise and minimum, by just exposing a PackedFunc that does the same job

**Comment by abergeron** [comment]
I'm not really sure how to do that, but if you think it's the best way, I'll try to come up with some code.

**Comment by tqchen** [comment]
see https://docs.tvm.ai/dev/runtime.html#packedfunc and https://github.com/dmlc/tvm/tree/master/src/api about how most API functions are exposed

**Comment by tqchen** [comment]
@abergeron please let me know if you need more information to proceed.

**Comment by tqchen** [comment]
@merrymercy do you mind taking this over?

**Comment by merrymercy** [comment]
I think we should not use packed function to keep the consistency of registry APIs, because all existing APIs do not use packed function.

@abergeron Here is an example of packed function

```c++
TVM_REGISTER_API("registry.remove")
.set_body([](TVMArgs args, TVMRetValue *ret) {
  std::string name = args[0];
  tvm::runtime::Registry::Remove(name);
});
```

```python
registry_remove = get_global_func("registry.remove")
registry_remove("a_function")
```

**Comment by tqchen** [comment]
close for now due to inactive status, @merrymercy @abergeron would be great if any of you can follow up

**Pull request closed without merging**
