### PR TITLE
[Relay] fix anf for reference and pattern matching

### PR DESCRIPTION
**Pull request by MarisaKirisame**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@ZihengJiang @srkreddy1238 @vinx13 please review.

**Comment by tqchen** [comment]
https://docs.tvm.ai/contribute/code_review.html#ensure-test-coverage

**Comment by tqchen** [comment]
@MarisaKirisame please add test cases to cover the change

**Comment by MarisaKirisame** [comment]
@tqchen test had been added.

**Pull request merged**
