### PR TITLE
Fix x86 Conv tuning tutorial

### PR DESCRIPTION
**Pull request by yzhliu**
@kevinthesun Could you verify?

### CODE REVIEW

**Comment by merrymercy** [comment]
There is a known issue of measurement on c5.9xlarge. As @kevinthesun and I discussed in #1585 .
At that time I provided a hack to fix it. But this is not upstreamed. 
I also found this issue on arm cpu.

Here I provide another easier hack to fix this. It works for arm cpu.  @kevinthesun Can you verify it on c5.9xlarge instance ?

```diff
diff --git a/python/tvm/autotvm/measure/measure_methods.py b/python/tvm/autotvm/measure/measure_methods.py
index ec3eb7e..60b463c 100644
--- a/python/tvm/autotvm/measure/measure_methods.py
+++ b/python/tvm/autotvm/measure/measure_methods.py
@@ -214,6 +214,7 @@ class RPCRunner(Runner):
         kwargs = {}
         if 'cuda' in self.task.target.keys or 'opencl' in self.task.target.keys:
             remote = request_remote(self.key, self.host, self.port)
+
             ctx = remote.context(str(self.task.target), 0)
             max_dims = ctx.max_thread_dimensions
             kwargs['check_gpu'] = {
@@ -460,7 +461,10 @@ def run_through_rpc(measure_input, build_result,
         if ref_input:
             args = [nd.array(x, ctx=ctx) for x in ref_input]
         else:
+            # create empty arrays on the remote device and copy them once.
+            # This can avoid some memory issues that make the measurment unreliable
             args = [nd.empty(x[0], dtype=x[1], ctx=ctx) for x in build_result.arg_info]
+            args = [nd.array(x, ctx=ctx) for x in args]
 
         costs = time_f(*args).results
         if len(costs) > 2:  # remove largest and smallest value to reduce variance
```

**Comment by yzhliu** [comment]
@merrymercy oh I was intended to say, what passes to topi_x86_conv2d_NCHWc should be output channel, while I also made a mistake - it should be `kernel[1][0]`

**Comment by kevinthesun** [comment]
This PR lgtm.

**Comment by merrymercy** [comment]
I mean if you run this tutorial without some fix to measurement, probably you will get wrong results.

**Comment by kevinthesun** [comment]
@merrymercy I'll verify your methods on c5.

**Comment by yzhliu** [comment]
@merrymercy Got it. Let's merge this and make another PR for the measurement fix.

**Comment by yzhliu** [comment]
@kevinthesun Got chance to verify?

**Comment by kevinthesun** [comment]
@merrymercy I just verified your method and it works for c5 instance.

**Pull request merged**
