### PR TITLE
Revert "Added tesnorizeation for avx2 based gemm."

### PR DESCRIPTION
**Pull request by tqchen**
@kimishpatel This PR is breaking the CI mainly because of some of the CI machine does not support the cpu feature. Can you send it in again and add additional guard so that it bypasses the test if the CI env does not support the instruction.

### CODE REVIEW

**Comment by tqchen** [comment]
http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/master/runs/1614/nodes/145/log/?start=0

**Comment by kimishpatel** [comment]
@tqchen, sorry about that, but that is strange. It should have skipped this test.

**Comment by tqchen** [comment]
I think there might be a difference between compiler supporting certain target and cpu has the corresponding feature

**Comment by kimishpatel** [comment]
I am wondering if CI is running on machine with AVX2 cpu support but the it is disabled. Will have to dig a bit into it.

**Comment by kimishpatel** [comment]
@tqchen, I might be grossly wrong here but I was able to run https://github.com/dmlc/tvm/blob/master/tests/python/contrib/test_gemm_acc16.py on non skylake machine, with the same "illegal instruction" error. Something is weird. This test also checks for the target, so I thought I will look at the corresponding code. 
https://github.com/dmlc/tvm/blob/master/src/codegen/llvm/llvm_common.cc#L165
It seems that by the time you get there you never get nullptr? (I am not familiar with llvm codebase but from what I understood it seemed that way). So once you lookup a target and get it, you can create target machine, but lookup does not use cpu string. So it is not clear how to check if particular target is available or not.
Anyways it is unlikely that this is broken but I was trying to understand why the test failed.

**Comment by soumith** [comment]
as Tianqi said, compiler supporting the target would be different from guarding if the CPU has that particular feature and skipping out.
Compiler supporting the target would mean compiler can successfully create binary that has AVX2 instructions.
Typically in pytorch, we guard this by runtime-checking if the CPU has AVX2, and if it doesn't, dispatching to the non-AVX routine. For example by using cpuinfo library to check the processor flags: https://github.com/pytorch/pytorch/blob/a23109e12e12db35ca48cf1f991d89304b4bfc73/aten/src/ATen/native/DispatchStub.cpp#L28

**Comment by tqchen** [comment]
@kimishpatel if you get a skylake machine and it still gives you illegal instructions, perhaps we need to look into the ASM being generated. You can do it by save the module to a .s file using https://docs.tvm.ai/api/python/module.html?highlight=module%20save#tvm.module.Module.save

**Comment by kimishpatel** [comment]
@soumith @tqchen that is correct. I was just pointing out that in that case checking if particular feature is supported or not seems broken no? On sky lake machine it runs ok. I think just the way we are checking is broken.

**Comment by kimishpatel** [comment]
If we are building for the current machine we probably need Cupid of the machine to check if compiled module will be executable.

**Pull request merged**
