### PR TITLE
Fix bug in ONNX importer

### PR DESCRIPTION
**Pull request by jroesch**
Fixes small bug in the ONNX importer that is very confusing, fix for #3079. 

The importer previously would default to scalars when input shapes were not provided. This instead requires the user to explicitly provide all input shapes.

### CODE REVIEW

**Comment by jroesch** [comment]
cc @zhreshold

**Comment by tqchen** [comment]
@jroesch @zhreshold please look into the CI case and decide an actionable item to move forward

**Comment by jroesch** [comment]
It looks like there was previously a bug in the old test case that was being silently ignored due the previous default. If there were no inputs in the constant fill case we still added an input to the graph even though we didn't pass one. The other fix would be we intended to pass an argument and to explicitly pass one.

**Comment by tqchen** [comment]
@zhreshold please https://docs.tvm.ai/contribute/code_review.html#approve-and-request-changes-explicitly

**Comment by tqchen** [comment]
Thanks @jroesch @zhreshold @yzhliu , this is now merged

**Pull request merged**
