### PR TITLE
Keep the order of arguments in generated kernel function

### PR DESCRIPTION
**Pull request by kun-zh**
To resolve the issue in 
https://discuss.tvm.ai/t/kernel-c-code-kernel-c-code-parameter-order-is-not-the-same-with-python-script-while-building-kernel/958 , in customized op, user want to keep the order of arguments in generated function. @tqchen can you review the PR, and give any ideas or better solution? Thanks.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @kun-zh Likely we do not need the field fix_order_args.  The args field before the split follows the order given to the build.  The main question is that during the procedure of split host device, the device function argument code happen in arbitrary order. 

This is not a bug for customized op as long as user directly calls the generate host function. Because the host code still calls into the device code using the correct order. If we want to solve this problem, then we will somehow try to order the arguments in the device code. 

Note that the arguments to the device code does not necessarily corresponds to the host argument(for example, a Buffer in the args could become the data field, or the shape arguments etc). So it is a bit somewhat undefined for the general case.

**Comment by kun-zh** [comment]
@tqchen Sure, the arguments doesn't need to be ordered because the host code which TVM generated can call the device code correctly. But If I only want use TVM as a standalone DSL compiler to generate device code , then use the other runtime framework to call it,  the framework should know the argument order in device function. We want to integrated TVM compiler into the other runtime framework automatically, only let user define the argument list in their DSL code. @Zaihua-Zhou

**Comment by tqchen** [comment]
That is fine, I am all for adding this support,  but I feel that the current implementation is not the best. First of all, we don't need to introduce the fixed_args list because the args in the function before split have the right order, we only need to have a way to order the Vars correctly after split

**Comment by kun-zh** [comment]
Thanks, tianqi. It is important for us, I will try as your suggestion, then refine the patch.

**Comment by xwang-91** [comment]
@tqchen  If user want to keep the order of arguments in generated function, such as ,if `mod = tvm.build(s, [input_a, input_b, res], "cce", name = kernel_name)`,so we want the device arguments  is `kernel_name( input_a, input_b,  res) {...}` .    And if `mod = tvm.build(s, [res，input_b, input_a], "cce", name =kernel_name)`,so we want the device arguments  is `kernel_name(res, input_b, input_a) {...}`.    They must corresponding.  So if we do not  use ` fix_order_args`, what should we do to deal with this ?

**Comment by tqchen** [comment]
First of all, if we build with ``` [input_a, input_b, res]```, the order of the input to the host side of the function, is the same(input_a, input_b, res), so we do not need fixed_order_args to store the original order information in the build (we already are).

The reason that the device side of the argument is different is that the order can be permutated determined when we split between host and device. This need to be addressed properly by ordering argument in the SplitDeviceCode pass. However, there is no strictly one to one mapping. Consider the following case, which can be generated by adding two tensors together(with the same length).

```c
void device_func(void* data1, void* data2, int n) {
}

void host_func(DLTensor* x1, DLTensor*x2) {
  void* ptr1 = x1->data;
  void* ptr2 = x2->data;
  int n = x1->shape[0];
  int n2 = x2->shape[0];
  assert(n == n2);
  device_func(ptr1, ptr2, n);
}
```

You can find that the signature in device_func does not directly correspond to the arguments in the host_func. In the best case, we can define a rule, for example, ptr1 traces back to x1, ptr2 traces back to x2, and we order them as ptr1 and ptr2, but how should we order n is an interesting question.

**Comment by xwang-91** [comment]
@tqchen  If we do not consider `int n`,can we get the the right  order of arguments `data1, data2`?

**Pull request closed without merging**
