### PR TITLE
[Relay] Fix reduce axis bug

### PR DESCRIPTION
**Pull request by altanh**
Fixes failure of `sum` and `all` on `axis=0`. Added regression tests as well.

### CODE REVIEW

**Comment by altanh** [comment]
cc @siju-samuel @jroesch

**Comment by altanh** [comment]
It looks like this change was undone in the past for #2439, but I can't see how `axis and isinstance(axis, int)` differs from simply `isinstance(axis, int)` other than evaluating to false when `axis=0`, since `isinstance(None, int)  == False`.

**Comment by jroesch** [comment]
We need to prevent against the axis being None, it should be `axis is not None and ...` what happens if you pass None right now?

**Comment by altanh** [comment]
Not quite sure I understand, unless the existing code was incorrect in keeping `None`:
```
>>> axis = None
>>> axis = [axis] if axis and isinstance(axis, int) else axis
>>> axis is None
True
```
For clarity, this demonstrates the bug this PR fixes:
```
>>> axis = 0
>>> axis = [axis] if axis and isinstance(axis, int) else axis
>>> axis == [0]
False
```
whereas with the fix:
```
>>> axis = 0
>>> axis = [axis] if isinstance(axis, int) else axis
>>> axis == [0]
True
>>> axis = None
>>> axis = [axis] if isinstance(axis, int) else axis
>>> axis is None
True
```
Otherwise TVM crashes since it expects an array of ints or None, from what I can tell.

**Comment by tqchen** [comment]
THanks, @altanh @jroesch, this PR is now merged

**Pull request merged**
