### PR TITLE
Fix PRelu layout in Relay

### PR DESCRIPTION
**Pull request by FrozenGene**
see discussion: https://discuss.tvm.ai/t/gluon-model-with-prelu-crash-in-relay-build/2071/6

@kevinthesun @eqy

### CODE REVIEW

**Comment by kevinthesun** [comment]
Maybe worth adding a test to cover this use case?

**Comment by FrozenGene** [comment]
> Maybe worth adding a test to cover this use case?

I will add it later.

**Comment by tqchen** [comment]
ping @FrozenGene

**Comment by FrozenGene** [comment]
I am a little busy this period. pls hold on of this pr, I will add test case as soon as possible. Sorry for this.

**Comment by FrozenGene** [comment]
@kevinthesun Have added the test case.

**Comment by jroesch** [comment]
ping @kevinthesun

**Comment by kevinthesun** [comment]
Thank you @FrozenGene for fixing this. This is now merged.

**Pull request merged**
