### PR TITLE
[Relay]resize op compute and schedule

### PR DESCRIPTION
**Pull request by siju-samuel**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by yzhliu** [comment]
Thanks! Please request review.

**Comment by siju-samuel** [comment]
@MarisaKirisame @jroesch @yzhliu @tqchen please help to review this PR. TIA

**Comment by MarisaKirisame** [comment]
LGTM

**Comment by yzhliu** [comment]
Thanks @siju-samuel @MarisaKirisame This is now merged.

**Pull request merged**
