### PR TITLE
[RUNTIME] v2: runtime support for rocm

### PR DESCRIPTION
**Pull request by adityaatluri**

### CODE REVIEW

**Comment by adityaatluri** [comment]
@tqchen , can you help me understand what part is failing?

**Comment by tqchen** [comment]
need to add things to here https://github.com/dmlc/tvm/blob/master/src/runtime/c_runtime_api.cc#L29

**Comment by adityaatluri** [comment]
Did add it though. https://github.com/adityaatluri/tvm/blob/rocm-init-v2/src/runtime/c_runtime_api.cc#L33

**Comment by tqchen** [comment]
OK was due to the jenkins sometimes cache an old version of the build and did not update the build. Let mean clean the workspace and retrigger the build

**Comment by adityaatluri** [comment]
I couldn't understand the source of the error. Is it normal that loading add_cpu.so loads all dependency rt libraries?

**Comment by tqchen** [comment]
Yes, when we do import tvm, i think it will load in the dependent runtime library, and somehow HSA cannot be loaded when there is no devices available?

**Comment by tqchen** [comment]
OK for now I think it might be better to not include rocm related stuffs into the linked libraries. We will just verifies that it compiles in the jenkins ci for now. Changed in https://github.com/dmlc/tvm/pull/387

**Comment by tqchen** [comment]
@adityaatluri Please run tests locally to verifies all testcases passes when linked to ROCM runtime
- tests/scripts/task_python_unittest.sh
- tests/scripts/task_python_intergration.sh

**Comment by adityaatluri** [comment]
Here is the log:
https://gist.github.com/adityaatluri/6f2cff50fd762aa83a4fd8772c124df0

**Comment by tqchen** [comment]
OK, please rebase against master. During running tests, enable LLVM and USE_RPC=1, this should be able to let you pass unittest. For now, we only need tests/python/unittests/test_runtime_ndarray to pass and rocm buffer works.

Later we might need to check the compiled libraries results

**Comment by adityaatluri** [comment]
Do you plan to run tests once AMD GPU gets added to CI?

**Comment by tqchen** [comment]
need to tweak the test env a bit. We currently relies on docker for building test env and need to check if anything like nv-docker is available

**Comment by tqchen** [comment]
For now let us do local verifications of tests

**Comment by adityaatluri** [comment]
Can you cook up test script for it so that I can report it for every pull request I create?

**Comment by tqchen** [comment]
The two script I listed before  should be fine, as long as you build with rpc and llvm enabled

**Pull request merged**
