### PR TITLE
Minor improve to assertion

### PR DESCRIPTION
**Pull request by larroy**
improve error message, remove unnecessary check

Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by tqchen** [comment]
I am not sure about the motivation of this particular constructor. I can understand sometimes we need to downcast size_t into uint32_t, but wouldn't it be better to ask the dev to downcast explicitly? The most natural arguments about the constructor are the constructor itself

**Comment by larroy** [comment]
Why do we have uint32_t as index in the graph? Any particular reason? Memory savings?

**Comment by tqchen** [comment]
The index node refers to the output index of the tensor. The number of outputs of an operator is not going to be bigger than 2^31. As a matter of fact,  there is no operator that has more than three outputs that I know of (except for split, which could results in 10 if the user specified so).

Given these considerations, using a 32bit integer is more than sufficient for this case.

**Comment by larroy** [comment]
Fair point. I will change it.

**Comment by larroy** [comment]
Fixed it.

**Comment by tqchen** [comment]
Thanks, @larroy , this PR is now merged

**Pull request merged**
