### PR TITLE
[Relay] Fix IncompleteType Alpha Equality Checking

### PR DESCRIPTION
**Pull request by joshpoll**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from others in the community.

### CODE REVIEW

**Comment by slyubomirsky** [comment]
Good catch

**Comment by tqchen** [comment]
I am not completely sure this should be the semantics for every alpha equal checking, as the same incomplete type appearing in similar locations naturally has certain meanings.

**Comment by joshpoll** [comment]
@tqchen I don't quite understand. Do you have specific examples where this is not the desired behavior? Both @MarisaKirisame and I have cases where this PR gives us the desired behavior.

**Comment by slyubomirsky** [comment]
Apologies for my inattentive reading, I thought the initial change was _adding_ a check for kind, not eliminating the pointer equality check. I agree that two different type vars should not be considered alpha-equal simply because they have the same kind (perhaps we could do the same thing as with ordinary vars? Add an explicit name/identity field to use for distinguishing type vars from each other?)

**Comment by MarisaKirisame** [comment]
@joshpoll I had been using incompletetypenode to signal 'infer for me'.
I switch to None and all is fine.

**Comment by joshpoll** [comment]
If we can use None instead of IncompleteType nodes, what is the purpose of the latter? Are they not meant to be specified by users but only used internally by the type checker? If that's the case, perhaps we should make a stronger/clearer distinction between these two types of nodes.

**Comment by joshpoll** [comment]
Looks like using None for a function return type causes a nullptr exception during alpha equality checking?

**Comment by joshpoll** [comment]
As long as we allow nullptrs in function return types and in variable types, I think I can fully switch my annotations to None instead of IncompleteType. I can close this PR and submit a new one with changes to alpha equality that add more type `defined()` checks if that sounds good to you all. I've already made the change in the text format branch.

**Comment by tqchen** [comment]
Supporting None sounds good

**Comment by joshpoll** [comment]
I think we still need to revise the semantics of alpha equality for IncompleteTypes, though, like Steven suggested, since with just pointer equality two structurally identical expressions aren't alpha equal.

**Pull request closed without merging**
