### PR TITLE
[nnvm] Add caffe2 frontend

### PR DESCRIPTION
**Pull request by hlu1**
The caffe2 nnvm frontend now supports three models from the caffe2 modelzoo (https://github.com/caffe2/models): squeezenet(v1.1), resnet50, and vgg19. 

@ajtulloch, @tqchen, @zhreshold, please review, thanks!

### CODE REVIEW

**Comment by tqchen** [comment]
@hlu1 Thanks for the contribution, can you clarify the difference between caffe2 model ingestion vs ONNX based conversion, would onnx frontend suffice to support caffe2 model?

**Comment by hlu1** [comment]
Mostly because of int8 quantization. ONNX quantization is WIP, but moving very slowly. The caffe2 int8 backend is being open sourced now (https://github.com/pytorch/pytorch/pull/13065). We don't want to blocked by the ONNX quantization work.

**Comment by zhreshold** [comment]
@hlu1 Before diving into details, on high level, the caffe2 converter is actually really similar to the onnx one, if bypass onnx work is your intention, can you verify if onnx/caffe2 converter can be differentiated with modular settings? 

Seems like the only difference is how you get the op sets, either by loading a onnx model or run caffe2 to get the blob list?

**Comment by tqchen** [comment]
I think given that caffe2 represents a more up to date state of pytorch/caffe2 models, it makes sense to bring in this frontend, but like @zhreshold suggested, maybe we could modularize the code so that onnx and caffe2 frontend shares most of the code, except for a few operator set conversion mechanism

**Comment by hlu1** [comment]
@tqchen and @zhreshold, thanks for the suggestion. I think it makes sense to modularize the code whenever possible. There are several differences between the onnx and caffe2 frontends:
1. How the opset is loaded. As @zhreshold noted, caffe2 loads the model by parsing caffe2.proto and onnx loads the model by parsing onnx.proto.
2. For the operators that are similar or even identical, mostly elementwise and math ops, the OpConverter can definitely be shared
3. The nn ops are where they differ the most, because:
- Caffe2 supports both NCHW and NHWC layouts. The float32 backend mostly uses NCHW, but the int8 backend is NHWC only. ONNX supports only NCHW.
- Caffe2 uses a larger set of arguments/attributes. For example, there are three ways to represent kernel shape: 'kernel', 'kernels', or 'kernel_h' and 'kernel_w', similarly for padding, strides, and dilations. 
- In some ops, caffe2 handles tensor flattening implicitly. For example. in the FC(dense) op, the input can be a 4D or 2D tensor, which is flattened into a 2D tensor inside the op.

  Given these differences, I find it hard to differentiate the caffe2/onnx converters with modular settings. For these ops, I think we need to re-implement the classmethod `_impl` at the very least.

**Comment by tqchen** [comment]
Please fix the lint error here http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-1981/2/pipeline and request another round of reviews when things are ready

**Comment by hlu1** [comment]
@tqchen, will do, thanks!

**Comment by tqchen** [comment]
@zhreshold @Huyuwei @kazum please help take a look

**Comment by tqchen** [comment]
also @ajtulloch who should be more familiar with caffe2

**Comment by ajtulloch** [comment]
This looks good to me correctness/code-reuse wise - and this also paves the way for allowing importing C2 int8 graphs (used by e.g. FBGEMM/QNNPACK/BoltNN HVX) into TVM. I think this is a useful addition to the TVM project.

**Comment by tqchen** [comment]
Please rebase against the master, @srkreddy1238 can you help review this PR?

**Comment by tqchen** [comment]
@hlu1 please fix the lint error here http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-1981/8/pipeline if there is no further comments from reviewers, I will merge it in 24 hours after the lint fix. cc @zhreshold @ajtulloch

**Comment by ajtulloch** [comment]
Sounds great, thanks @tqchen.

**Comment by tqchen** [comment]
@ajtulloch can you please https://docs.tvm.ai/contribute/code_review.html#approve-and-request-changes-explicitly?

**Comment by hlu1** [comment]
@tqchen and @ajtulloch, the lint error is now fixed. Thanks

**Comment by tqchen** [comment]
Thanks, @hlu1 @ajtulloch @zhreshold, this is now merged

**Pull request merged**
