### PR TITLE
[TOPI] Setting up AutoTVM template for Intel Int8 conv2D

### PR DESCRIPTION
**Pull request by anijain2305**
As Title

@kevinthesun @yzhliu

### CODE REVIEW

**Comment by comaniac** [comment]
Would you consider the fallback config?

**Comment by anijain2305** [comment]
> Would you consider the fallback config?

@comaniac , the fallback config is already set. Here, we directly use the NCHW fallback config. This happens during the alter_op_layout conversion from conv2d to conv2d_nchwc_int8.

Next week, I am going to a do a much larger sweep of ic and oc to check robustness. I can incrementally build then.

**Comment by comaniac** [comment]
> @comaniac , the fallback config is already set. Here, we directly use the NCHW fallback config. This happens during the alter_op_layout conversion from conv2d to conv2d_nchwc_int8.
> Next week, I am going to a do a much larger sweep of ic and oc to check robustness. I can incrementally build then.

Make sense. Thanks for the clarification.

**Comment by yzhliu** [comment]
Thanks @anijain2305 @comaniac @kevinthesun

**Pull request merged**
