### PR TITLE
[Relay][AD][WIP] Ensure autodiff can handle recursion in global functions

### PR DESCRIPTION
**Pull request by slyubomirsky**
While trying to eliminate nats from the tuple, I encountered a bug in the autodiff tests that appeared to be due to global variables not being eliminated from the gradient and having the types fail to match.

I attempt to address that error here by having global vars eliminated from the gradient and inlining them using a let binding to ensure recursion can still be preserved. However, I'm getting some weird errors here that I think may be due to other parts of AD: I notice free variables ending up in the gradient where they shouldn't and got a type error I could not make sense of.

@MarisaKirisame, could you please advise as to whether the intentions of these changes are reasonable?

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@slyubomirsky I dont think this is the right approach, as this is NonModular.
If I have a function that, has 10k line dependency (think of a really deep network, like a deep resnet), this pass will make a single 10k line function. Then, we has to do all other pass on this gigantic thing. This doesnt scale.
What we should do is, has an AD interface, that we can transform arbitary global Function into.
Suppose the original function has type T, the result function should be BPType -> ADType(T):
given a backpropagator, it specialize itself to the Gradient Version at runtime.
This interface has the additional property that it enable NLP as well: an LSTM cant be backproped using the Gradient function as of right now, as it take list as input.

**Comment by slyubomirsky** [comment]
I'm not sure I fully understand. Do you mean that for each global `g`, we should add to the module `g_grad` and replace references to `g` with references to `g_grad`?

**Comment by MarisaKirisame** [comment]
@slyubomirsky yes.

**Comment by slyubomirsky** [comment]
Okay I will try implementing that, should be straightforward

**Comment by slyubomirsky** [comment]
Going to withdraw this PR for now, as trying to fix this bug has exposed a few open design questions in AD that we can resolve later.

**Pull request closed without merging**
