### PR TITLE
[PASS] enable small vars reuse big buffer

### PR DESCRIPTION
**Pull request by xqdan**
enable B and C reuse A1 buffer, before this patch, B(200 int16) took all space of A1(200 float32) 
```
with ib.for_range(0, 10, name="j") as j:
            A = ib.allocate("float32", 200, name="A", scope="local.L0A")
            A1 = ib.allocate("float32", 200, name="A1", scope="local.L0A")
            A[j] = 1.2
            A1[j] = 1.3
            B = ib.allocate("int16", 200, name="B", scope="local.L0A")
            B[j] = tvm.const(1, "int16")
            C = ib.allocate("int16", 200, name="C", scope="local.L0A")
            C[j] = tvm.const(1, "int16")
            D = ib.allocate("int16", 200, name="D", scope="local.L0A")
            D[j] = B[j] + C[j]
            E = ib.allocate("int16", 400, name="E", scope="local.L0A")
            E[j] = tvm.const(1, "int16")
            A2 = ib.allocate("float32", 200, name="A2", scope="local.L0A")
            A2[j] = A[j]
```
also add a case for 
```
// then start looking at smaller buffers.
      for (auto it = mid; it != begin;) {
        --it;
        StorageEntry *e = it->second;
        if (e->attach_scope_ != attach_scope) continue;
        if (e->scope != scope) continue;
        if (e->elem_type != op->type.element_of()) continue;
        const_free_map_.erase(it);
        return e;
      }
```

### CODE REVIEW

**Comment by tqchen** [comment]
The current logic have a few problems, and I think we need to think the reuse algorithm more carefully

What will happen when the smaller array get out of scope, can they get used by bigger ones again? It seems that we cannot. This brings the question on if it is worth of doing this kind of split

**Comment by xqdan** [comment]
what do you mean by 'get out of scope', exceeding the space of defined scope?

**Comment by xqdan** [comment]
without this patch, there is a bug in current logic when bigger reusing small buffers, i'll fix it first.

**Comment by tqchen** [comment]
don't get what is the problem, can you elaborate? or give an example

**Comment by xqdan** [comment]
case:
```
def test_alloc_seq_type3():
    ib = tvm.ir_builder.create()
    n = tvm.var("n")
    with ib.for_range(0, n, name="i") as i:
        with ib.for_range(0, 10, name="j") as j:
            A = ib.allocate("int16", 200, name="A", scope="local.L0A")
            A[j] = tvm.const(1, "int16")
            B = ib.allocate("int16", 200, name="B", scope="local.L0A")
            B[j] = tvm.const(1, "int16")
            B1 = ib.allocate("int16", 200, name="B1", scope="local.L0A")
            B1[j] = A[j] + B[j]
            C = ib.allocate("int16", 400, name="C", scope="local.L0A")
            C[j] = tvm.const(1, "int16")
            D = ib.allocate("int16", 400, name="D", scope="local.L0A")
            D[j] = tvm.const(1, "int16")
            E = ib.allocate("int16", 400, name="E", scope="local.L0A")
            E[j] = C[j]

    body = ib.get()
    body = tvm.ir_pass.StorageRewrite(body)
```

after pass
```
// attr [A] storage_scope = "local.L0A"
allocate A[int16 * 400]
for (i, 0, n) {
  for (j, 0, 10) {
    A[j] = (int16)1
    A[(200 + j)] = (int16)1
    A[j] = (A[j] + A[(200 + j)])
    A[j] = (int16)1 # D length 400 
    A[(200 + j)] = (int16)1 # E length 400  overlap with D
    A[(200 + j)] = A[j]
  }
}
```

**Comment by tqchen** [comment]
OK, this seems to be a problem, but I do not understand how current patch fix that problem, can you elaborate on what is happening here?

**Comment by xqdan** [comment]
can not. I'll sent another pr. close this for now.

**Pull request closed without merging**
