### PR TITLE
[FRONTEND] [HYBRID] Infrastructures for manipulating hybrid IR body directly.

### PR DESCRIPTION
**Pull request by were**
- Some infrastructures to manipulate the IR body directly
- Change the test of hybrid GPU to a case with sync bar (actually no explicit bar insertion needed)

### CODE REVIEW

**Comment by merrymercy** [comment]
How about supporting unroll?

**Comment by were** [comment]
@merrymercy Nice suggestion! Let me do it maybe?

**Comment by tqchen** [comment]
This is done by IR level transformation. However, I was wondering if we could have a more structured form of the operator in C++, that consists of data parallel loop nest, plus body(can be any stmt).

And we can use the same infrastructure(relations, axis) to manipulate the data parallel axis

**Comment by were** [comment]
I think we can do it, but so far it is only for raw stmt body.

**Comment by tqchen** [comment]
move the discussion to #1384 close this for now, let us reopen once we have a clear plan

**Pull request closed without merging**
