### PR TITLE
Update measure_methods.py

### PR DESCRIPTION
**Pull request by Jokeren**
Is it supposed to be a bug? @merrymercy 

Besides, could you test the autotuning script on more Android devices, it seems really unstable for me.

### CODE REVIEW

**Comment by Jokeren** [comment]
@tqchen , even if it is not a bug, the comment looks pretty confusing

**Comment by tqchen** [comment]
As far as i can tell, the ndk is switched off by default. so the original code is correct. You will need to pass use_ndk=True to the measure_option. 

Maybe you can followup on specific problems you encountered when tuning android on the https://discuss.tvm.ai/ and we can help improve this process together

**Comment by Jokeren** [comment]
Thanks for your comment.

For this problem, if kwargs.get('use_ndk', False), which means ndk should not be invoked, in the following line we should not call ndk.create_shared. That’s why I maintain that the original code is incorrect. I found this problem from receiving error message like load_module_tar func is not found.

**Comment by tqchen** [comment]
You will need to pass in build_func="ndk" in your measure option, which will automatically set use_ndk to be True in kwargs

**Comment by tqchen** [comment]
see also NOTE in https://docs.tvm.ai/tutorials/autotvm/tune_nnvm_arm.html#set-tuning-options

@merrymercy maybe it makes sense to update the tutorial to pass in build_func and measure_func as keyword arguments by default

**Comment by tqchen** [comment]
To be clear, kwargs is a dict, and kwargs.get("use_ndk", False) will return the value inside the dict if it is available, if not, it will return False

**Comment by tqchen** [comment]
That is, kwargs.get("use_ndk", False) is not equivalent to `kwargs["use_ndk"]== False`, rather it is 

```python
 kwargs["use_ndk"] if "use_ndk" in kwargs else False
```

**Comment by merrymercy** [comment]
1. Unstable issue
    What's your phone? What's is unstable?
    You should turn on 'Keep RPC Alive' on the APP. On my pixel2 phone, although the android system reports the app is crashed, the app just works well. You can see whether the tuning looks like normal.

2. The code is correct. If you set `build_func='ndk'` in the option, then `kwargs = {"use_ndk": True}`. Otherwise it does not contain the key "use_ndk", so `kwargs.get("use_ndk", False)` is False.

3. You can report your unstable error by enabling log. 
Put these lines in the beginning of your script
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
remove the progress_bar callback function in

```python
        # do tuning
        tuner_obj.tune(n_trial=min(n_trial, len(tsk.config_space)),
                       early_stopping=early_stopping,
                       measure_option=measure_option,
                       callbacks=[
                           # autotvm.callback.progress_bar(n_trial, prefix=prefix),  #### REMOVE THIS LINE
                           autotvm.callback.log_to_file(tmp_log_file)])
```
These will print every tuning results to the screen.

**Comment by Jokeren** [comment]
Thanks you two, finally got it, just a stupid grammar issue...

I will try and report if I have other problems.

**Pull request closed without merging**
