### PR TITLE
[BUILD] Fix LLVM libraries cmake symbol

### PR DESCRIPTION
**Pull request by grwlf**
Original issue discussion:
https://discuss.tvm.ai/t/llvm-error-option-registered-more-than-once-while-loading-libtvm-so/269/3

Reference:
https://github.com/CastXML/CastXML/issues/102#issuecomment-372488956

Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from others in the community.

### CODE REVIEW

**Comment by grwlf** [comment]
OK Probably one have to condition on LLVM versions here. I'll try to come with a solution. Locally, cmake is not able to build correct libraries without this.

**Comment by tqchen** [comment]
Unfortunately, we cannot simply use LLVM, can you investigate further by looking into what is in LLVM_LIBS.

The current rule makes the assumption that llvm is packed in libLLVM, which is not always true

**Comment by grwlf** [comment]
OK, I understand the concerns. On our machine LLVM_LIBS contains a long list of static libraries entries followed by a dynamic library entry, like this:

    LLVMDemangle;LLVMSupport;LLVMTableGen;LLVMCore;...;LLVMXRay;LLVM

The initial error was caused by a singleton, which was executed twice: first time by a static part of llvm, coming from libtvm.so, second time by dynamic library. Note, that systems which don't distribute dynamic libraries of LLVM are not affected. Jenkins seems to be lucky in this sence.

For the affected systems, the problem may be solved by either 1) linking with only static llvm or 2) linking with only dynamic llvm. Initially we suggested the first approach, but the latest patch implements the second one which also works.

This version is less invasive, since it changes only one line of code. From the other hand, this way we wouldn't be able to use libtvm.so with libLLVM.so in applications, since both libraries would try to execute singleton and the second attempt will fail.

    $ g++  -std=c++11 src/argmax/argmax0.cpp  -ltvm -lLLVM 
    $ ./a.out
    : CommandLine Error: Option 'disable-symbolication' registered more than once!
    LLVM ERROR: inconsistency in registered CommandLine options

**Comment by tqchen** [comment]
is it possible to detect the LLVM_LIBS first to see if both static and dynamic libs co-exists? The current way might not work if there is only dynamic library(and it get removed)

**Comment by grwlf** [comment]
The latest patch prefers dynamic LLVM if it is available and defaults to static linkage otherwise. According to 'Build LLVM with CMake' guide, dynamic library contains all the components, so the basic presence check should be enough.

Just discovered, that Jenkins uses explicitly-defined llvm-config, like `set(USE_LLVM llvm-config-4.0)`. So its build script bypasses the affected "USE_LLVM ON" branch completely.

**Pull request merged**
