### PR TITLE
Add PyTorch converter

### PR DESCRIPTION
**Pull request by Koin-Flipper**
Add support for PyTorch models.

### CODE REVIEW

**Comment by yidawang** [comment]
Please request reviewers. Also, is this related to #2494?

**Comment by Koin-Flipper** [comment]
Indeed, it is a first step toward resolving #2494. I'm unable to request reviewers as I suppose I don't have access. Do you have any suggestions of who to CC?

**Comment by yidawang** [comment]
Nice! Please request [reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md) by CCing them directly. Perhaps someone who has experience on the frontend?

**Comment by Koin-Flipper** [comment]
Sounds good, thanks! @siju-samuel @jroesch can you please take a look?

**Comment by hlu1** [comment]
Why nnvm? Have you considered adding it to the relay frontend?

**Comment by Koin-Flipper** [comment]
Upgrading to Relay is a work in progress. As far as the model coverage for the converter in this PR, goes, NNVM is sufficient.

**Comment by tqchen** [comment]
Given that we are moving toward using relay as our next generation infra, please consider directly change the PR with relay support

**Comment by Koin-Flipper** [comment]
Thanks, given the changes necessary to switch from NNVM to Relay, I'll go ahead and close this PR and open a new one that's implemented with Relay.

**Pull request closed without merging**
