### PR TITLE
[NNVM] Add symbol squeezenet

### PR DESCRIPTION
**Pull request by merrymercy**
Add squeezenet symbol in test. This is mainly used for performance benchmark.

### CODE REVIEW

**Comment by merrymercy** [comment]
This PR also fixes the CI error of #1435 #1432

**Comment by TaoLv** [comment]
Any instructions about how to run the performance benchmark of this squeezenet as well as other imagenet models? I would like to evalute the performance of this models on Intel CPUs. Thanks.

**Comment by tqchen** [comment]
@TaoLv please open a thread at https://discuss.tvm.ai/

**Comment by TaoLv** [comment]
Thanks, @tqchen. Since the description of this PR says it's mainly for performance benchmarking, so I think it's proper to ask for the usage of it here. Anyway, I have created a topic in the forum. https://discuss.tvm.ai/t/how-to-benchmark-the-imagenet-models-in-tvm-nnvm/484

**Comment by tqchen** [comment]
No problem @TaoLv :) The reason we prefer opening threads vs discussing via issue/in PR is that PR get can get ignored and issues can get closed. Posting things on forum will allow others to participate and learn from the topic

**Pull request merged**
