### PR TITLE
use pytest instead of nosetest

### PR DESCRIPTION
**Pull request by MarisaKirisame**
nosetest is in maintenance mode, so we should switch to the more modern framework.

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@tqchen if you add 'import topi' to test_codegen_llvm.py, and run it, it will failed. do you has any idea?

**Comment by kevinthesun** [comment]
https://github.com/dmlc/tvm/pull/3595 should fix your issue.

**Comment by MarisaKirisame** [comment]
@tqchen @kevinthesun can you guys help review?

**Comment by tqchen** [comment]
Thanks @MarisaKirisame

**Pull request merged**
