### PR TITLE
add configuration about assert stmt in code generation

### PR DESCRIPTION
**Pull request by baowenlei**
This PR is to add build configuration of whether generate assert statement.
The reason is that assert statement could hurt performance, but still useful for debug purpose.

Please see the discussion here.
https://discuss.tvm.ai/t/disable-assert-in-runtime/2152

About the code change, I am not quite sure my PR is a best way to achieve the goal,
such as the location and name. So welcome fix and suggestions! 

Thanks,

### CODE REVIEW

**Comment by tqchen** [comment]
We want this to be a runtime option in the codegen (through build_config), instead of the macro that is configured during compile time.

**Comment by baowenlei** [comment]
@tqchen .Thanks for the feedback. It seems there is a misunderstanding. 
Just to confirm, do you mean to have an option in the tvm::build_config() API to have the assertion on or off ? 

Thanks,
-W

**Comment by tqchen** [comment]
yes

**Comment by baowenlei** [comment]
That means python/Java API also need to change accordingly ?

**Comment by FrozenGene** [comment]
@baowenlei I am interested in the performance. Do you have the data between disabling assert and enabling assert? Thanks.

**Comment by baowenlei** [comment]
@FrozenGene Cannot recall any particular number, but the difference is obvious and users would like to avoid any cost of that IMO. Thanks.

**Comment by tqchen** [comment]
@baowenlei, please update the PR. 

It would also be nice to do some benchmarks, my guess is that these assertions won't create additional cost due to the bigger overhead in the kernel loops

**Comment by FrozenGene** [comment]
@baowenlei I wish we could have benchmark. Because I try to one convolution. I don't notice the improvement.

**Comment by tqchen** [comment]
ping @baowenlei

**Comment by baowenlei** [comment]
@tqchen @FrozenGene Thanks for the feedback. 
It seems that we do not have any record of the difference. 
But the problem is that for release version of the code, the assertion will be gone.
However, here the assertion is instrument in llvm level, which will exist in either release or debug version.
The point is that user should have option to have it in their generated code or not. 

Regarding to the PR, I am sorry I recent does not have time to work on that. Tight with other works. But I will update that once I got time. Feel free to close this for now.

Thanks!

**Comment by tqchen** [comment]
close for now due to inactive status

**Comment by tqchen** [comment]
Thanks @FrozenGene @baowenlei

**Pull request closed without merging**
