### PR TITLE
[Relay] Add printing for ADT Type

### PR DESCRIPTION
**Pull request by MarisaKirisame**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@joshpoll @weberlo @icemelon9 can you guys review?

**Comment by wweic** [comment]
This is printing, not parsing(in the title)?

**Comment by MarisaKirisame** [comment]
@wweic sorry, i am sleepy.

**Comment by weberlo** [comment]
looks good to me

**Comment by icemelon9** [comment]
Thanks everyone. This is now merged.

**Pull request merged**
