### PR TITLE
Add dilate_filter scheduling to conv2d_nchw

### PR DESCRIPTION
**Pull request by nishi-t**
This PR modifies conv2d schedule to handle conv2d with `dilation` on cuda. Could you review this and give me advice?  @Huyuwei 

Related github issue: 
[[OP] Support dilation in conv2d](https://github.com/dmlc/nnvm/issues/402)

### CODE REVIEW

**Comment by Huyuwei** [comment]
I am afraid this doesn't generate correct schedule we want. Please first add a testcase to see the result.

**Comment by nishi-t** [comment]
@Huyuwei Sorry for the delay. I think that your PR fixes this issue and my PR finished the role.  Can I close this?

**Comment by Huyuwei** [comment]
@nishi-t Yes, this one can be closed. Thanks for the effort :)

**Comment by nishi-t** [comment]
@Huyuwei OK, I'll close this. Thanks for your help.

**Pull request closed without merging**
