### PR TITLE
[Relay] fix 'please use input parameter mod warning' triggered in build_module

### PR DESCRIPTION
**Pull request by MarisaKirisame**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@yzhliu @ZihengJiang @merrymercy @vinx13 @jroesch can you guys give some review? everytime I run pytest it flush a screen of warning so I'd like this merged.

**Comment by tqchen** [comment]
@MarisaKirisame please rebase against the master. Please check the CI error

**Comment by tqchen** [comment]
Thanks, @MarisaKirisame , this PR is now merged

**Comment by MarisaKirisame** [comment]
@tqchen should we make the warning an error since it is now unused?

**Comment by tqchen** [comment]
We will keep the deprecating warning for one release cycle then remove the support

**Pull request merged**
