### PR TITLE
[Relay] Add hd,tl,nth for list in Prelude

### PR DESCRIPTION
**Pull request by wweic**
Adding these common helpers for `list`. Following OCaml's name.

### CODE REVIEW

**Comment by wweic** [comment]
@MarisaKirisame @slyubomirsky Please take a look.

**Comment by MarisaKirisame** [comment]
LGTM.
I think this is a good time to discuss partiality introduced by pattern matching. rn they fail with internal error, but it pass typechecking without warning or error.

I think we should sort of add a 'partial' annotation and require match to be annotated as such, if it is partial.

It could be implemented by having a boolean field in Match.

Another option is, provide an explicit panic construct that signal a runtime error, force all match to be total, provide a partial match syntax helper that add a default case that throw "not matched".

@jroesch @tqchen wdyt?

**Comment by wweic** [comment]
@MarisaKirisame Or we can follow other general purpose language(like `OCaml`) to add exceptions, for cases we don't expect to match, throw an exception. I guess this is similar with the `panic` construct you suggested.

**Comment by MarisaKirisame** [comment]
@wweic there's two orthgonal issue:
0: what to do at runtime when incomplete match come up
1: how do we provide safety mechanism to avoid user accidentally writing incomplete match

for ocaml, (0: is exception, and 1: is compiler warning).

I agree with your suggestion on (0:), but I am not sure about following ocaml on (1:).

**Comment by slyubomirsky** [comment]
The code, other than the open question of how to handle incomplete matches, LGTM

For my part, I think if we do want to allow incomplete matches (I would prefer Relay to always be total, but that could be impractical), then we should check at compile-time that matches be complete and require the user to annotate deliberately partial matches.

**Comment by tqchen** [comment]
@MarisaKirisame @slyubomirsky please https://docs.tvm.ai/contribute/code_review.html#approve-and-request-changes-explicitly

**Comment by tqchen** [comment]
Thanks @MarisaKirisame @slyubomirsky @wweic this is now merged

**Pull request merged**
