### PR TITLE
Adopt pylint suggestion to use dict.get.

### PR DESCRIPTION
**Pull request by mjs-arm**

### CODE REVIEW

**Comment by tqchen** [comment]
This one seems to be a bit too pedantic :) is it possible to disable it in pylintrc?

**Comment by mjs-arm** [comment]
> This one seems to be a bit too pedantic :) is it possible to disable it in pylintrc?

Of course.  I'll respin it shortly.

**Comment by tqchen** [comment]
ping @mjs-arm

**Comment by mjs-arm** [comment]
> ping @mjs-arm

Sorry, I really did mean 'shortly' but events overtook.... respin disables the consider-using-get globally via pylintrc

**Pull request merged**
