### PR TITLE
[Relay] [Fix] BatchMatmul cannot be fused. mark it as opaque.

### PR DESCRIPTION
**Pull request by MarisaKirisame**
@tqchen

Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by tqchen** [comment]
A better fix would be to actually fix the topi to make it easy to fuse batch_matmul

**Comment by tqchen** [comment]
@merrymercy @Hzfengsy can you check to see if we can fix the batch_mul 's schedule template?

**Comment by vinx13** [comment]
@MarisaKirisame Can you give a test case where fusion doesn't work?

**Comment by tqchen** [comment]
@MarisaKirisame please act on the comment and provide an example

**Comment by MarisaKirisame** [comment]
@tqchen @vinx13 this comeup in some private repo, that has lots of code. we do not rely on it, so I will close and open if it come up again.

**Pull request closed without merging**
