### PR TITLE
[FRONTEND][COREML]More ops are added

### PR DESCRIPTION
**Pull request by siju-samuel**
The following ops and their corresponding testcases are added to COREML Frontend

- [x] AverageLayerParams
- [x] MaxLayerParams
- [x] MinLayerParams
- [x] LRNLayerParams

Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from others in the community.

### CODE REVIEW

**Comment by siju-samuel** [comment]
@zhreshold  @yzhliu @srkreddy1238  Could you please do the review. Thanks.

**Comment by siju-samuel** [comment]
@yzhliu Rebase done.

**Comment by zhreshold** [comment]
LGTM.

**Comment by tqchen** [comment]
Thanks @zhreshold @siju-samuel , this is now merged

**Pull request merged**
