### PR TITLE
[Relay][Parser] simplify build script, remove python 2 support 

### PR DESCRIPTION
**Pull request by MarisaKirisame**
This pr remove the antlr jar finding process and use antlr4 directly instead.
Also, it remove python2 support for the parser, as tvm ditch python 2 suppoty.

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@joshpoll @slyubomirsky @tqchen

**Comment by yzhliu** [comment]
As @zhiics suggested, do we also need to remove some of the auto-generated file in grammar/py3 ?

**Comment by MarisaKirisame** [comment]
@yzhliu I removed all the files in py3 and did a clean make. It also removed the .gitattributes but it didnt seem to be of any use.

**Comment by zhiics** [comment]
And we probably also what to update the .gitignore file to ignore the update of them, right?

**Comment by MarisaKirisame** [comment]
@zhiics the generated parser file is included, because we do not expect everyone working on relay to has ANTLR installed. This way only ppl modifying the parser need to install ANTLR.

**Comment by tqchen** [comment]
@yzhliu please followup on this PR

**Comment by yzhliu** [comment]
Thanks @MarisaKirisame @zhiics @tqchen

**Pull request merged**
