### PR TITLE
[TOPI] Add GPU SSD

### PR DESCRIPTION
**Pull request by Laurawly**
This PR adds the following ops:
nms including GPU sorting
multibox_prior for GPUs
and multibox_detection

Tests for individual ops can be found in topi/tests/python/test_topi_vision.py

@tqchen @kevinthesun @yzhliu @yidawang plz help review or comment, thanks!

### CODE REVIEW

**Comment by liangfu** [comment]
Supporting vision operators for gpu is great. But it is less flexible with another copy of operators written with ir_builder. Is it possible to create schedules for IR? Or as suggested in #1322, vision operators should be migrated to use hybrid script? If these are not possible, a rewrite of the IR is fine.

**Comment by kevinthesun** [comment]
We will migrate ssd related ops to hydrid frontend. IR builder version serves for a first stable version to support ssd on GPU.

**Comment by tqchen** [comment]
@were @srkreddy1238 please review

**Comment by tqchen** [comment]
Thanks @Laurawly for the contribution, this is now merged

**Pull request merged**
