### PR TITLE
[NNVM] Allow target specific behaviors in precompute prune

### PR DESCRIPTION
**Pull request by masahi**
The precompute_prune function uses llvm backend to run a graph. But I think it is better to use the user-supplied target. For example, different backends may want to use different implementations of winograd filter transform, because the optimal filter transform layout depends on backends.    

@merrymercy Can you have a look ?

### CODE REVIEW

**Comment by masahi** [comment]
The values of the result should be the same, but the layout can be different. Take Winograd F(2x2, 3x3) , for example. The straightforward layout of filter transform for GPU backend is (4, 4, in_channel, num_filter), while for cpu backend, I found it better to be in (in_channel/8, num_filter/8, 4, 4, 8, 8).

**Comment by srkreddy1238** [comment]
@masahi 
I see winograd is about the scheduling the computation.

To my knowledge the precompute pass returns a sub graph out of the main graph which is independent or graph inputs and can be precomputed. Some set of nodes here becomes params (and some params may get dropped.).

Precompute pass doesn't know any thing about target. Not sure how this will have an impact with layout.

I think I am missing some thing here ...!

**Comment by masahi** [comment]
If you are not familiar with winograd convolution, you can read about it in [this cool paper](http://openaccess.thecvf.com/content_cvpr_2016/papers/Lavin_Fast_Algorithms_for_CVPR_2016_paper.pdf).

The precompute pass returns a new graph (not a subgraph) and parameters. When you invoke nnvm compiler like this,

 ```
 graph, lib, params = nnvm.compiler.build(
                net, args.target, shape={"data": data_shape}, params=params)
```
the returned params can be different from the passed params. For example, the layout of filter weight can change from OIHW to OIH8i8o. This is what 'AlterOpLayout' pass will do for x86 target when opt_level is 3.

By making precompute pass target-aware, we can modify how things get precomputed, depending on targets.

**Comment by srkreddy1238** [comment]
@masahi 
Thanks for the information :+1: .

**Comment by merrymercy** [comment]
I think we shouldn't change precompute pass. 
To precompute winograd filter transformation,  we can make two nnvm symbols (one for kernel transformation, one for the remaining computation), and register alter_op_layout to split the original conv2d symbol to these two symbols.
Since alter_op_layout is target aware, we can choose the correct symbols in alter_op_layout function.

**Comment by masahi** [comment]
Yes, I made two nnvm symbols, one for kernel transform and another for actual convolution, just like you said. And I have two different kernel transforms for cpu and gpu backend.

The problem is,  precompute_prune function always uses llvm backend [here](https://github.com/dmlc/tvm/blob/master/nnvm/python/nnvm/compiler/build_module.py#L341), even if I want to compile for CUDA. So during precompute phase, cpu kernel transform is chosen, even though I want to run the kernel transform registered for cuda backend.

**Comment by kevinthesun** [comment]
My understanding is the same as @merrymercy. We define layout related stuffs, such as kernel pre-packing in alter_op_layout, which is target specific. Then in precompute the pre-pack is executed. llvm should be enough, since the execution patten has been already well defined alter_op_layout and result is the same.

**Comment by masahi** [comment]
ok, let me give a concrete example. In Mali backend's winograd, the kernel transform declared [here](https://github.com/dmlc/tvm/blob/master/topi/python/topi/mali/conv2d.py#L577) is in layout (alpha, alpha, K // bna, C, bna). We can move the kernel transform to precompute phase, but if later someone implements winograd convolution without kernel transform for other backends, all other backends need to adapt the same kernel transform layout. This is because precompute pass always targets the llvm backend

**Comment by kevinthesun** [comment]
https://github.com/dmlc/tvm/blob/master/topi/python/topi/x86/conv2d.py#L157-L162 This is how we do kernel prepack for avx-512. Kernel prepack is done in pre-compute pass and we don't need to specify "llvm -mcpu=skylake-avx512" for pre-compute. This method should be able to apply to other targets. Is there anything missing for your use case?

**Comment by masahi** [comment]
Yes, I am fairly familiar with how x86 backend does 'direct' NCHW[8,16]c convolution, including how kernel prepacking is done during precompute. But, here, I'm talking about filter transform for 'Wingrad' convolution, which is totally different.

**Comment by merrymercy** [comment]
Can you share your implementation of nnvm symbol?

**Comment by masahi** [comment]
sure, it's [here](https://github.com/masahi/tvm/blob/nnvm-winograd/nnvm/python/nnvm/top/nn.py#L143-L174). Relevant topi ops are available for x86 and cuda, in the same branch. 

I've done this for my learning purpose, so I will not send any PR. I'm waiting for your 'official' implementation.

**Comment by kevinthesun** [comment]
No. kernel prepack and other layout transformation can be applied to other backends. @Laurawly working with OpenCL. No target change is required for pre-compute.

**Comment by masahi** [comment]
ok, will have a look.

**Comment by masahi** [comment]
In #1420, @rajh619 said intel HD with opt level 3 produced wrong outputs, but opt level 2 works fine. With opt level 3, AlterOpLayout pass will run, which replaces NCHW conv with NCHWc. I think _alter_conv2d_layout for intel HD is not running, but instead x86's _alter_conv2d_layout is chosen.

**Comment by kevinthesun** [comment]
That issue comes from a recent change in layout transformation api.

In conv2d_alter_layout, we specify "kernel_layout" attribute. Note that for different targets we may want different kernel layouts. In nnvm, AlterOpLayout pass will modify the graph and insert layout transformation operators from how conv2d_alter_layout is defined. After graph modification is done, pre-compute can execute to compute the kernel prepack and doesn't require target information, since the result will be the same. 

Another reason to keep pre-compute target agnostic is that we don't have to compile model on the target device.

**Comment by masahi** [comment]
ok, I confirmed that  intel HD's _alter_conv2d_layout is correctly running. But I cannot get my two different  winograd kernel transforms, one for cpu and another for cuda, work without this PR.

I should clarify that I am not using existing _alter_op_layout for my winograd implementation. I have added another, similar one.

**Comment by merrymercy** [comment]
In your infer_shape for winograd, you has a parameter to specify the layout. (https://github.com/masahi/tvm/blob/3d72fc7b81bed8615229dd2dc213ae65ad6bd0eb/nnvm/src/top/nn/convolution.cc#L154)
Why don't just we pass this parameter to topi function. In topi decleration, we can make the `tvm.compute` according to this argument.

**Comment by masahi** [comment]
ah, right. I don't need to dispatch winograd_filter_transform to backends inside topi. I can return different kernel transform depending on parameters in topi.nn.winograd_filter_transform(...).

Thanks for clearing up my confusion and pointing me in the right direction!

**Comment by merrymercy** [comment]
@masahi We don't need to specify layout in `winograd_weight_transform`. We can use nnvm symbol transpose, reshape to tweak the layout in `alter_op_layout` for different backend.  e.g. https://github.com/merrymercy/tvm/blob/441d4b459d3ab6527c25ed77902b0dceeed6788d/topi/python/topi/arm_cpu/conv2d.py#L499

For `winograd_without_weight_transform`, my current strategy is that we don't check the shape of weight tensor. So it should work for all backends.

**Comment by masahi** [comment]
nice!

**Pull request closed without merging**
