### PR TITLE
[Relay] Keras frontend upsample and 1 channel conv2d fixes

### PR DESCRIPTION
**Pull request by jwfromm**
[This Discussion post](https://discuss.tvm.ai/t/keras-import-dimensions-dont-match-in-3-layer-example/3974) found two bugs in Relay. The first was a silly mistake I introduced with the Resize rework (#3788 ) caused by defaulting to the wrong layout for upsample in the Keras frontend. I've resolved this issue and fixed the corresponding test. The second bug occurs when a convolution with 1 filter attempts to determine the shape of its weights. Relay checks for group convolutions by seeing if the number of channels equals the group size, however we obviously shouldn't if the number of channels is 1. I've added a new test to check for this failure in the future.

### CODE REVIEW

**Comment by tqchen** [comment]
@kazum please manage the PR , @jwfromm please request reviews from folks by tagging them next time

**Comment by jwfromm** [comment]
@kazum, can you take a look? These are pretty minor fixes so it should be quick.

**Comment by jwfromm** [comment]
@masahi, maybe you can take a look instead?

**Comment by kazum** [comment]
@jwfromm, sorry for being late.  I'll take a look today.

**Pull request merged**
