### PR TITLE
[RELAY][PASS] Bind, FoldConstant

### PR DESCRIPTION
**Pull request by tqchen**
- [x] Refactor type_subt->Bind(overloaded name) and move to type_functor.cc
- [x] Add support of Bind which bind params(free vars) to certain expression
    - This is useful to bind parameters as a constant into the IR during inference.
- [x] Support FoldConstant
   - This is useful for folding contents that can be pre-computed, in nnvmv1 it was called precompute_prune.
- Support constant node in graph runtime backend.
   - constants will be generated as params dict.

The general flow now becomes:
- bind params into IR as constant
- Run optimizations, including constant folding
- In graph runtime codegen, the constants nodes are then lifted out as params

### CODE REVIEW

**Comment by tqchen** [comment]
cc @yzhliu @zhiics @ZihengJiang @jroesch @MarisaKirisame @PariksheetPinjari909 please review

**Comment by tqchen** [comment]
The side effect is checked by is_stateful, I think the folding pass should work with functions of recursion, by ignoring recursive calls. But indeed they don't unroll the recursion if that is what you mean

**Comment by MarisaKirisame** [comment]
@tqchen tuplegetitem(tuplenode(...)) will just take the expr
but if some expr in tuplenode went into infinite recursion, or has effect, it will change the behavior of the program

**Comment by tqchen** [comment]
I see, indeed, we will need side effect check pass and possibly combine dead code elim into folding. For now it is fine as the program is side-effect free

**Comment by jroesch** [comment]
Looks good to me we can follow up on those issues afterwards.

**Pull request merged**
