### PR TITLE
[RPC] Add the IPV6 support for server side auto tuning

### PR DESCRIPTION
**Pull request by llyfacebook**
We mainly make the auto-tuning work under both IPV4 and IPV6 network.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for contributing the PR, please request reviewers

**Comment by tqchen** [comment]
@eqy please moderate this PR

**Comment by tqchen** [comment]
@eqy you can directly merge this in once things are green :)

**Comment by eqy** [comment]
Thanks @llyfacebook, merging.

**Pull request merged**
