### PR TITLE
Vendor gtest

### PR DESCRIPTION
**Pull request by kazimuth**
This PR adds googletest as a submodule to make it easier for new contributors to run tests; it's challenging to globally install googletest on OS X, this makes things a little simpler. It's a small download (5mb), a fast build (like 5 seconds), and has a permissive license, so i don't forsee this causing problems. Of course, it is another vendored dependency, so if people don't think it's worth it I understand.

I used the 1.7.0 release tag since that was what travis seemed to be using.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for the PR. We tried to minimize the number of submodules so I think we should not include it as source deps. The docker recipe https://github.com/dmlc/tvm/blob/master/docker/install/ubuntu_install_core.sh#L8 is a good way to install gtest (build it and copy the file to somewhere that is added to C_INLCUDE_PATH and LIBRARY_PATH)

**Comment by hcho3** [comment]
@tqchen @kazimuth If adding a git submodule is not desired, we can use CMake to automatically download and compile GTest. See https://github.com/dmlc/dmlc-core/blob/3ffea8694adf9c0363f9abbf162dc0e4a45b22c5/test/unittest/CMakeLists.txt#L33

**Comment by mjs-arm** [comment]
There are (at least) three different mechanisms in use in the tree to include foreign/3rd party material.
1) The docker infrastructure / scripts that build docker images for build/test
2) The git submodule mechanism populating 3rdparty
3) build/test scripts that directly download material (one instance in tree Im aware of, there may be more).

Having build/test scripts fetch material on the fly is not ideal from several perspectives:
- It spreads the download / cache logic through out the code base
- It means 'clean builds' repeatedly download material (a major issue for those behind low bandwidth links).  Putting appropriate caching behaviour in place behind docker etc is straight forward, it is not so when with de-centralized down load code.

From an architecture perspective it makes more sense to solve the same problem using one mechanism rather than multiple mechanisms.

Is there a particular reason not to extend the current docker scripts to handle this gtest install?

**Comment by tqchen** [comment]
docker is usually preferred for software dependencies, in the case of gtest we do want to use docker, and it is already handled in the docker.

As for testing data, we use the test script to fetch test data on the fly and cache then locally. This is mainly because test data is not part of the software and users may want to run them optionally.

**Comment by junrushao1994** [comment]
The issue of having gtest as a system lib is that it could be compiled using a different compiler, which may cause minor troubles for users to build from scratch. For docker, I feel like it is fine.

**Comment by hcho3** [comment]
I suppose if a Dockerfile is provided, it's fine

**Pull request closed without merging**
