### PR TITLE
[TOPI][FIX] Typo in schedule template for conv2d_direct (#3648)

### PR DESCRIPTION
**Pull request by mingwayzhang**
* Fix the tile_rx and tile_ry issue.

    Note that this patch depends on pull request #9 in tvm-distro.

    Please review. Thanks.

### CODE REVIEW

**Comment by tmoreau89** [comment]
@cbalint13 you are also proposing a version change on CUDA tophub schedule; can you coordinate to serialize the changes?

**Comment by cbalint13** [comment]
> @cbalint13 you are also proposing a version change on CUDA tophub schedule; can you coordinate to serialize the changes?

* Will rebase everything once this very 3717 is merged.
So please merge this first, I have more work pending on our side (even beyond the simple tophub update).

Thank you !

**Comment by mingwayzhang** [comment]
> Changing the cuda TOPHUB version is also proposed in #3606
> 
> I suggest you revert the tophub changes, and keep the changes local to the `conv2d_direct.py` file, and change the title labels to `[TOPI][FIX] Typo in schedule template for conv2d_direct`

Are you suggesting that the schedule function `schedule_conv2d_nchw` in `conv2d_direct.py` using the wrong schedule config? From my understanding, all schedule configs with name `top_nn_conv2d` are consumed by `schedul_conv2d_nchw`.

**Comment by tmoreau89** [comment]
Thank you for the clarifications

**Pull request merged**
