### PR TITLE
[Relay] Add logical operators

### PR DESCRIPTION
**Pull request by abergeron**
This is a follow-up to https://github.com/dmlc/tvm/pull/2453, to port the operators that were added to Relay.

The one thing I'm less than certain about is the support_level since I've yet to see some actual documentation about what it means.

### CODE REVIEW

**Comment by slyubomirsky** [comment]
I would venture to guess (though I am not an authority on it) that a support level of 1 would be appropriate for core, basic operators the logical connectives

**Comment by tqchen** [comment]
See https://docs.tvm.ai/langref/relay_op.html for support level explaination. I think it should be level 4

**Comment by srkreddy1238** [comment]
@abergeron look good to me.

Update the support_level as per @tqchen advice. Also update the support_level for NNVM too.

**Comment by MarisaKirisame** [comment]
Should it be defined using RELAY_REGISTER_BINARY_OP? It mean it work on *any* dtype.

**Comment by abergeron** [comment]
I've fixed the support level.

I don't think those operators are applicable for all types, but I don't know how to limit the types.

**Comment by tqchen** [comment]
Thanks, @MarisaKirisame @abergeron @srkreddy1238 , this is now merged. 

We could use a followup PR to update type relation to assert bool types, but since it is not strictly necessary, we can go with the current ver for now

**Comment by tqchen** [comment]
@abergeron please send a followup to update https://docs.tvm.ai/langref/relay_op.html

**Comment by MarisaKirisame** [comment]
@tqchen I can do it, but I have tons of task next week. I will open a issue. If noone does it next week I will pick it up, does it sound good?

**Comment by tqchen** [comment]
@MarisaKirisame Sounds good, go ahead and open an issue

**Pull request merged**
