### PR TITLE
[PASS] Enhance gpu verify pass

### PR DESCRIPTION
**Pull request by merrymercy**
Check the mismatch of axis lengths.
This error is easy to meet when we schedule cooperative fetching

cc @eqy

### CODE REVIEW

**Comment by eqy** [comment]
Do we have another way of supporting multi-axis bind?
I think the typical CUDA style for doing this if the axes are independent is to just do

```
if (threadIdx.x ... < axis_size)
     do_something;
```

**Comment by merrymercy** [comment]
It is a problem of the compiler. But this pattern typically cannot make the performance better. So we can leave this problem latter and use this verification pass to ensure correctness.

**Comment by tqchen** [comment]
I am going to merge this for now as this is an improvement over previous one. However,  note that if there are two thread extent, there can actually be the different thread bound if a schedule contains multiple stages of kernels, a better way is to not check the string, but check by address IterVar

**Comment by merrymercy** [comment]
@tqchen My code can handle this case. I only do check inside a kernel

**Pull request merged**
