### PR TITLE
Minor fix of warnings raised by  -Wreturn-std-move and -Wself-assign-overloaded

### PR DESCRIPTION
**Pull request by junrushao1994**
My clang keeps complaining about it. 

Update:

For example,

```
/path/to/tvm/src/relay/pass/type_infer.cc:727:14: warning: local variable 'func' will be copied despite being returned by name [-Wreturn-std-move]
      return func;
             ^~~~
/path/to/tvm/src/relay/pass/type_infer.cc:727:14: note: call 'std::move' explicitly to avoid copying
      return func;
             ^~~~
             std::move(func)
```

The reason for this is that copy elision is not always turned on, so in this case, `std::move` is not a pessimization.

See this [thraed](https://reviews.llvm.org/D43322) in LLVM for details.

### CODE REVIEW

**Comment by tqchen** [comment]
hmm, I am not sure, in theory these can be optimized by copy elision and we should not explicit move

**Comment by junrushao1994** [comment]
I feel weird as well, but clang-7 keeps asking me to explicitly write std::move.

**Comment by junrushao1994** [comment]
Looks like “-Wreturn-std-move” reports stuff that are not eligible for RVO

**Comment by tqchen** [comment]
OK, I will merge them in for  now

**Pull request merged**
