### PR TITLE
[ARITH] Use floordiv for the deduce bound

### PR DESCRIPTION
**Pull request by umangyadav**
Solves #3974

### CODE REVIEW

**Comment by umangyadav** [comment]
@tqchen @ZihengJiang  @kimishpatel  @xqdan  Can you review this? thanks.

**Comment by kimishpatel** [comment]
Following a quick glance Not sure but unconditional floordiv may not be right when I put Expr cannot be simplified to constant. E.g n/3 vs floordiv(n,3). C integer div is always round towards zero.

**Comment by umangyadav** [comment]
> Following a quick glance Not sure but unconditional floordiv may not be right when I put Expr cannot be simplified to constant. E.g n/3 vs floordiv(n,3). C integer div is always round towards zero.

@kimishpatel  I don't completely understand your example.  Can you elaborate more? 

`floordiv` will be converted to `truncdiv`  (C equivalent) during the lowering where based on the dividends and divisor's sign information. Is that what your concern was that `floordiv` is not the same as `C` div ?

**Comment by umangyadav** [comment]
@tqchen @kimishpatel  

I am more concerned about the case where analyzer can not prove that `(result_ % operand == 0)` for some reason despite being divisible. 

For the sake of an example, let' say 
` (3 * cc2 + 6)  % 3` and let's say `analyzer_` fails to prove it equal to `0` then bounds would come out wrong for the `kGreater`. 

In fact, one such case where proving modulo is zero fails is here: 
https://github.com/dmlc/tvm/blob/18188f4ba3f53cc1dab765b8a0d932d21db0ae8a/tests/python/unittest/test_arith_deduce_bound.py#L124

I agree with the removing the tight bounds assumption and removing the conditions directly in the loop partition now.

**Comment by umangyadav** [comment]
ping @tqchen  @ZihengJiang

**Comment by ZihengJiang** [comment]
@umangyadav Hey, this PR looks good overall. Could you add the example in the issue https://github.com/dmlc/tvm/issues/3974  as a test case?

**Comment by umangyadav** [comment]
@ZihengJiang  I'd thought about it, but I found it not necessary, as the existing test cases already had one of such cases. Before, it was using relaxed bounds as the benchmark. So, it was all passing. I've modified the benchmark (expected result) to account for floor division now. 
 
I can add the test anyway if you think it would be better.

**Comment by ZihengJiang** [comment]
No worries. This PR has been mergred. Thanks! @umangyadav

**Pull request merged**
