### PR TITLE
[DOCKER][FRONTEND] Run DarkNet tests

### PR DESCRIPTION
**Pull request by kazum**

### CODE REVIEW

**Comment by kazum** [comment]
@siju-samuel could you help solve the CI error?
```
test CRNN layer ... *** Error in `python3': corrupted double-linked list: 0x000000001fdca8a0 ***
```
This is related to the discussion in https://discuss.tvm.ai/t/libdarknet2-0-so-source-code/1743.

**Comment by icemelon9** [comment]
@kazum @siju-samuel What's the status on this PR?

**Comment by kazum** [comment]
I've updated nnvm darknet tests to pass CI.  @siju-samuel @icemelon9, can you help review this?

**Comment by icemelon9** [comment]
Could you also help add darknet test to Relay? The test code is located at tests/python/frontend.

**Comment by kazum** [comment]
@icemelon9, adding Relay darknet frontend is still on-going. #2773

**Pull request merged**
