### PR TITLE
Support onnx tensor attribute and Constant op

### PR DESCRIPTION
**Pull request by fumihwh**
- support onnx tensor attribute
- support onnx Constant op

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for the contribution, can you add a regression testcase that simply constructs a single op and run the conversion?

**Comment by fumihwh** [comment]
@tqchen Sure

**Comment by tqchen** [comment]
awesome, let me know when it is added

**Comment by pallabdatta** [comment]
@tqchen, @fumihwh  -- Do I need to submit a review or someone else will do it!? so that this is pushed to the main TVM git repo?

**Comment by tqchen** [comment]
pending testcases that covers the change

**Comment by srkreddy1238** [comment]
@tqchen 

This can be merged. The test case I am adding for Shape(#1333) covers this case as well.

**Comment by fumihwh** [comment]
@srkreddy1238 Thanks for info.

**Pull request merged**
