### PR TITLE
[Rust] Fixes "common" sub crate using nightly and master

### PR DESCRIPTION
**Pull request by paddyhoran**
Fixes [3964](https://github.com/dmlc/tvm/issues/3964).

Also, removes warning for stabilized feature [type_alias_enum_variants](https://github.com/rust-lang/rust/pull/61682)

### CODE REVIEW

**Comment by paddyhoran** [comment]
cc @nhynes

**Comment by paddyhoran** [comment]
I hope so.  I'd like to add support for windows and was hoping to get CI up for it eventually.  I'll try and take a look.  Where is it currently disabled?

I see Azure Pipelines running but where are the jobs defined?

**Comment by tqchen** [comment]
@nhynes please feel free to merge it in :) We can send another pr to reenable rust ci

**Comment by tqchen** [comment]
@nhynes can you send a followup PR to r-enable rust-ci?

**Comment by nhynes** [comment]
> followup PR to renable rust-ci?

There's a linking issue that's been resolved in #2885. I'll re-enable Rust CI once that lands.

**Comment by paddyhoran** [comment]
@nhynes @tqchen it looks like there might an issue with this, see [here](https://discuss.tvm.ai/t/failed-to-compile-rust-bindings-tvm-common/4106).

I'm thinking the types generated by bindgen are platform specific(I'm on windows), but I need to confirm.

**Pull request merged**
