### PR TITLE
[Relay] add fatal

### PR DESCRIPTION
**Pull request by MarisaKirisame**
Fatal can has any type, and it's semantic is to abort execution with a message.
This PR also add a `complete` field to pattern matching, with default to true.
Only match with complete=false can has incomplete pattern.
Additionally, it fix evaluating an incomplete pattern for Partial Eval - previously it will be an internal compiler error, now it will emit fatal in the generated code.

@wweic @ZihengJiang @yzhliu can you guys help review?

### CODE REVIEW

**Comment by tqchen** [comment]
Any reason why it should be a new AST node as opposed to a special operator?

**Comment by wweic** [comment]
adding `Fatal` as a special Op sounds like a good idea.

**Comment by MarisaKirisame** [comment]
fatal introduce a whole new effect (stopping the program), so that more distinction is made by keeping it as a seprate construct.
as an analogy, one can also make RefCreate, RefRead, RefWrite a Op, but imo that's hiding the fact that they change the semantic in a subtle way.

**Comment by slyubomirsky** [comment]
I think I agree with Tianqi; I am not sure a `fatal` expression is as deep a change to the semantics as, say, `ref`. I suppose it might be hard to make such a comparison since exiting the program is left to syscalls in many languages, but a special `fatal` function with the type `() -> ()` wouldn't require adding AST nodes and probably wouldn't require much messing with language internals.

**Comment by slyubomirsky** [comment]
I guess having `fatal` as a separate AST node will ensure that passes _must_ deal with it (or ignore it) and won't need to special-case their function call visit case, for example. I suppose that qualifies as a reason to have it as a separate expr (with type `()`, I'd guess), perhaps?

**Comment by wweic** [comment]
agree with @slyubomirsky. `fatal` should be similar to `exit` function in c, it's a normal function. Unless we want to implement general exception mechanism, then AST change seems more appropriate.

**Comment by tqchen** [comment]
based on the discussion so far and the current inactive status, i propose to close this PR, let us continue to open new ones that uses a function to represent FATAL

**Pull request closed without merging**
