### PR TITLE
[VTA][TOPI] Conv2d transpose (deconvolution) operator support

### PR DESCRIPTION
**Pull request by tmoreau89**
This PR brings conv2d_transpose (deconvolution) support to VTA. Much of this work credit goes to @merrymercy.

### CODE REVIEW

**Comment by tmoreau89** [comment]
conv2d_transpose was successfully tested on `pynq` and `sim`; tuned schedules updated in: https://github.com/uwsampl/tvm-distro/commit/78cd3331edc670e3f41891070fddd92835dcb2e1

**Comment by tmoreau89** [comment]
@tqchen @merrymercy @jroesch please review

**Comment by merrymercy** [comment]
The implementation uses a direct IR rewrite to do the tensorization for `conv2d_transpose` (rather than `tvm.tensorize`)
I don't know whether it is acceptable.

And some part is hard-coded. (the constants 1, 16)
https://github.com/dmlc/tvm/blob/5616a5101aeb832f295b90b1d6b19f87f228d02e/vta/python/vta/ir_pass.py#L697-L707

**Comment by jroesch** [comment]
@merrymercy afaik the previous VTA passes use a lot of specialized tvm::Expr rewriting might be out of scope for the PR. If you think we should fix maybe we can use a tracking issue to avoid bit-rot?

**Comment by tmoreau89** [comment]
I can take care of eliminating the constants

**Comment by tmoreau89** [comment]
removed the hard coded parts

I would opt to merge this in, and address the IR rewrite issue in a follow up PR in order to make sure that this operator does not bit rot @jroesch

**Comment by merrymercy** [comment]
Okay, we can get this in after the hard coded part is removed.

**Comment by jroesch** [comment]
It looks like Thierry addressed the comments, I am going to merge feel free to rollback or followup if you have more feedback Lianmin.

**Pull request merged**
