### PR TITLE
[Frontend][MXNet] ones zeros ones_like zeros_like ops support

### PR DESCRIPTION
**Pull request by imorinaga**
This PR supports 6 symbols in MXNet frontend.

@srkreddy1238 @nishi-t Could you please do the review. Thanks.

### CODE REVIEW

**Comment by nishi-t** [comment]
@imorinaga Could you rebase the most recent master?

**Comment by imorinaga** [comment]
@nishi-t Thank you for comments! rebase done.

**Comment by nishi-t** [comment]
please add tests for these operators

**Comment by yzhliu** [comment]
@imorinaga Any updates?

**Comment by imorinaga** [comment]
argmax and argmin support is deleted.
Output dtype of these are fp32 in MXNet.
However, these are int32 in NNVM, Tensorflow, coreml and onnx.

**Comment by nishi-t** [comment]
Thank you for adding tests. If the point you check you have pointed out is a testing problem for argmin and argmax, #1908 may be able to fix it.

**Comment by imorinaga** [comment]
What I mean is not a testing interface problem.
To support argmax Symbol, I think out_dtype interface is needed on nnvm.symbol.argmax.

**Comment by nishi-t** [comment]
@imorinaga OK. I don't have sure knowledge of the return type and couldn't confirm it from the [document](https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.argmin). But, If argmin and argmax return the indices as float32 in mxnet, we would need to discuss how to support it. 
BTW, In this PR, do you intend to support only operators excluding these?

**Comment by imorinaga** [comment]
@nishi-t Yes, we

**Comment by imorinaga** [comment]
@nishi-t 
Yes, I want to support only ones, ones_like, zeros and zeros_like in this PR. Should I change the PR title?
BTW, I accidentally closed this PR so I've reopened. Sorry for confusing.

**Comment by nishi-t** [comment]
@imorinaga  yes, I'd suggest changing the title.

**Pull request merged**
