### PR TITLE
[FRONTEND][TENSORFLOW] Simplify input shape

### PR DESCRIPTION
**Pull request by alexeyr**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

Depends on #2105.

### CODE REVIEW

**Comment by alexeyr** [comment]
This gives some warnings when running tests, like

> [14:16:31] /workspace/src/romanov/tvm/src/schedule/bound.cc:110: not in feed graph consumer = compute(input0_red_temp, 0x478efb0)
> [14:16:31] /workspace/src/romanov/tvm/src/schedule/bound.cc:110: not in feed graph consumer =  compute(input0_red_temp, 0x478efb0)

and

> WARNING:autotvm:Cannot find config for target=llvm, workload=('conv2d', (4, 8, 8, 176, 'float32'), (1, 1, 176, 32, 'float32'), (1, 1), (0, 0), (1, 1), 'NHWC', 'float32'). A fallback configuration is used, which may bring great performance regression.

**Comment by icemelon9** [comment]
@alexeyr Could you resolve the conflicts to latest master?

**Comment by srkreddy1238** [comment]
@alexeyr  changes related to Unstack and Split(V) are already merged.
I think input_shape simplification may not be required as a node may have multiple outputs.

**Comment by alexeyr** [comment]
@icemelon9 Updated.
@srkreddy1238 This is taken into account: even if a node has multiple outputs, each input of another node uses only one of them and we still have a 1-element list there: https://github.com/dmlc/tvm/blob/021099f8d7d9cc59ae9ee872edde45803983d45c/nnvm/python/nnvm/frontend/tensorflow.py#L1235-L1243.

**Comment by alexeyr** [comment]
@srkreddy1238 Yes, this pull request doesn't fix any bugs, it is intended to simplify code while producing the exact same result. I've now verified that it actually does that: 

I get the 

> ...int_set.cc:514: cannot evaluate set type Cast

and other warnings when running the tests from IPython on the first try and don't get them after repeating. This happens both in `master` and with this pull request.

**Pull request merged**
