### PR TITLE
[FRONTEND][TENSORFLOW] Enable strided_slice with fix.

### PR DESCRIPTION
**Pull request by srkreddy1238**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by srkreddy1238** [comment]
cc @nishi-t @siju-samuel @yzhliu welcome to review.

**Comment by srkreddy1238** [comment]
cc @joyalbin

**Comment by srkreddy1238** [comment]
@nishi-t  & @yzhliu Can you take look at this PR. 
This was a fix for a long time back disabled strided_slice.

**Comment by tqchen** [comment]
Thanks @srkreddy1238 this is merged

**Pull request merged**
