### PR TITLE
Parser CI trigger

### PR DESCRIPTION
**Pull request by tqchen**
trigger CI of parser changes

### CODE REVIEW

**Comment by tqchen** [comment]
cc @joshpoll

**Comment by joshpoll** [comment]
Odd. has the docker install script been rerun on the gpu since antlr was added to it?

**Comment by tqchen** [comment]
The docker is updated to the latest. You can  reproduce locally via docker/bash tvmai/ci-gpu then run build

**Comment by joshpoll** [comment]
@tqchen I fixed ci locally on the relay-text-format branch. It should now (hopefully) fail with assert False inside the tests indicating the parser tests run and antlr is found.

**Comment by tqchen** [comment]
@joshpollseems there is still a problem

**Comment by joshpoll** [comment]
I changed the docker install scripts with my most recent commit. Does that require a different sort of update?

**Comment by tqchen** [comment]
Ah, OK, so you need to run the parser test in CPU right? Yes, the docker is not instant, since we cache the docker image locally and rebuilt only if necessary.

**Comment by tqchen** [comment]
Can you send the Docker change as a separate PR? Let us also keep antlr installation in GPU docker, so that we can turn it on later.

**Comment by joshpoll** [comment]
I moved to cpu docker so I could reproduce locally. In principle there's no reason it couldn't run on gpu I just wanted to eliminate potential sources for error.

**Comment by joshpoll** [comment]
#2191.

**Comment by tqchen** [comment]
@joshpoll see latest error http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-2153/4/pipeline

**Comment by joshpoll** [comment]
I wasn't sourcing /etc/profile to update `$JAVA_HOME`. Fixed in text format branch.

**Comment by tqchen** [comment]
@joshpoll can you update your PR so that it does not rely on the change of the install_java.sh(which requires us to update java all over again. Likely you can source it in Jenkinsfile before you run cmake.

**Comment by joshpoll** [comment]
Ok. I moved it to the make function in the Jenkinsfile

**Comment by joshpoll** [comment]
everything looks good. I think we need to enable antlr on GPU again so it will run the parser tests

**Comment by joshpoll** [comment]
unfortunately it may require another dockerfile retrigger

**Comment by joshpoll** [comment]
nevermind it won't be required

**Comment by joshpoll** [comment]
I modified the Jenkinsfile to use antlr on gpu.

**Pull request closed without merging**
