### PR TITLE
[FRONTEND][TENSORFLOW] Some bug fixes for tensorflow NCHW data_format

### PR DESCRIPTION
**Pull request by vv1133**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by vv1133** [comment]
Please review @srkreddy1238 @alexeyr

**Comment by zhiics** [comment]
@vv1133 Could you please add some description about what bugs are we fixing? If possible, please add a test to verify the effect.

**Comment by vv1133** [comment]
> @vv1133 Could you please add some description about what bugs are we fixing? If possible, please add a test to verify the effect.

- TensorFlow bias_add with data_format NCHW should reshape inputs[1] to [c, 1, 1] first like below.

        if attr['data_format'] == 'NCHW':
            bias_shape = attr['_input_shapes'][inputs[1]]
            bias = _op.reshape(inputs[1], newshape=tuple([bias_shape, 1, 1]))
        else:
            bias = inputs[1]
        return _op.add(inputs[0], bias)

- The previous code of transposing weight with data_format NCHW in frotend/tensorflow.py function _conv:

            tmp_shape = [tmp_shape[ii] for ii in (3, 2, 0, 1)]
            inputs[1] = _sym.transpose(inputs[1], axes=(3, 2, 0, 1))
TensorFlow DepthwiseConv2d weights shape: [H, W, C, DEPTH_MULT]
But refer to "./nnvm/src/top/nn/convolution.cc: Conv2DInferShape" weights_shape should transpose to [C, DEPTH_MULT, H, W]. So the transpose shape should be [2, 3, 0, 1] when the opname is "depthwise".

**Comment by srkreddy1238** [comment]
@vv1133 sorry for the delay, I will try to review this in next 2 days.

**Comment by srkreddy1238** [comment]
@vv1133   can you help to add a regression test ?

**Comment by tqchen** [comment]
ping @vv1133

**Comment by vv1133** [comment]
> @vv1133 can you help to add a regression test ?

Hi @srkreddy1238 ,I have added some test, please review, thanks!

**Comment by tqchen** [comment]
ping @srkreddy1238

**Comment by srkreddy1238** [comment]
@vv1133 sorry for the delay and thanks for the test cases.
I see CI failed due to some flaky test case (raised #3396). Please re trigger.

**Comment by tqchen** [comment]
@vv1133 the commit history seems to be messed up, please consider reapplying your patch on a clean fork

**Comment by vv1133** [comment]
> @vv1133 the commit history seems was messed up, please consider reapplying your patch on a clean fork

OK, I have updated a PR: #3514

**Pull request closed without merging**
