### PR TITLE
Fix gather_nd in Relay

### PR DESCRIPTION
**Pull request by hqucms**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by hlu1** [comment]
Could you add test cases to cover this?

**Comment by tqchen** [comment]
ping @hqucms can you please add a testcase?

**Comment by icemelon9** [comment]
@hqucms What's the status on this PR?

**Comment by hqucms** [comment]
Test cases added in https://github.com/dmlc/tvm/pull/3442/commits/08892d45a2cc4344c108bd5c513488fb2bf634f4. They would fail without the fix.

And sorry for the long delay -- I was occupied by other tasks last month and could not find time to look into this.

**Comment by tqchen** [comment]
Thanks @hqucms @hlu1 @icemelon9 !

**Pull request merged**
