### PR TITLE
[TOPI] 1bit dense operator on x86_64

### PR DESCRIPTION
**Pull request by Huyuwei**
TODO:

- [x] optimize schedule

### CODE REVIEW

**Comment by Huyuwei** [comment]
For matrix multiplication C = A (1, 1024) x B (1000, 1024):
- llvm naive schedule for float dense is 1043us tested on Intel® Core™ i5-6600K CPU (single thread)
- binary dense is 63us (single thread)
- cuda schedule for float dense is 21us tested on GTX1080

More optimizations for binary dense will be explored. Then binary conv will be added.

**Comment by tqchen** [comment]
if there is an external function in GPU that support pop count, then we can hook it in as in https://github.com/dmlc/tvm/blob/master/src/codegen/intrin_rule_cuda.cc#L39 and tvm.popcount should work for GPU as well

**Comment by Huyuwei** [comment]
CUDA has __popc and __popcll http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__INT.html#group__CUDA__MATH__INTRINSIC__INT_1g43c9c7d2b9ebf202ff1ef5769989be46

**Comment by tqchen** [comment]
pls let me know when this is ready to be merged

**Comment by Huyuwei** [comment]
Ok, within this week.

**Comment by tqchen** [comment]
@Huyuwei let us update this and merge it in

**Comment by Huyuwei** [comment]
For matrix multiplication C = A (1, 1024) x B (1000, 1024):
- llvm naive schedule for float dense is 1043us tested on Intel® Core™ i5-6600K CPU (single thread)
- binary dense is 16us (single thread)
-------------------------------------------------

For matrix multiplication C = A (1024, 1024) x B (1024, 1024):
- 1 thread binary dense: 46.1 ms
- 2 thread binary dense: 8.7 ms
- 4 thread binary dense: 4.6 ms

As we have noticed, the performance gain from 1 thread (46.1ms) to 2 thread (8.7ms) is too large and seems unreasonable.

When I remove ``s[C].parallel(s[C].op.axis[0])`` from the schedule, the result is 16.8 ms for single thread, much better than 46.1 ms.

**Comment by tqchen** [comment]
please let me know when it is ready to merge. For single threaded parallel, one useful thing for stableness is to use persistent threading, where we can set parallel launch point differently than loop, and loop over multiple internal parts

**Comment by tqchen** [comment]
this is merged in for now. we can followup with other improvements and ops

**Pull request merged**
