### PR TITLE
[Relay][OP] Fix bias_add default axis

### PR DESCRIPTION
**Pull request by icemelon9**
Change the default axis in bias_add from 1 to -1

### CODE REVIEW

**Comment by junrushao1994** [comment]
The CI issue is due to [this line](https://github.com/dmlc/tvm/blob/master/tests/python/relay/test_pass_alter_op_layout.py#L81) and [this line](https://github.com/dmlc/tvm/blob/master/tests/python/relay/test_pass_alter_op_layout.py#L271)

**Comment by icemelon9** [comment]
@junrushao1994 I'm investigating whether we should go with this change... I realize that bias_add with default axis=1 works good with conv, but requires batch flatten for dense op. I'll follow up on this pr in a few days.

**Comment by yzhliu** [comment]
any update?

**Comment by icemelon9** [comment]
I decide to change the MXNet converter to explicit set axis=-1 in the bias_add.
@junrushao1994 @yzhliu Could you review again?

**Comment by junrushao1994** [comment]
It looks good. Let's wait for the CI to complete

**Comment by icemelon9** [comment]
@junrushao1994 @jroesch CI has passed. Could you help review the pr?

**Pull request merged**
