### PR TITLE
[WIP] [Relay] [VTA] rewrite graphpack to be more generic and work for scope.

### PR DESCRIPTION
**Pull request by MarisaKirisame**

### CODE REVIEW

**Comment by jroesch** [comment]
@MarisaKirisame @tmoreau89 can you guys work together to update this and get it merged? might be a good time for tech transfer.

**Comment by tmoreau89** [comment]
This PR is out of date and should probably be closed.

**Comment by MarisaKirisame** [comment]
@tmoreau89 I have some free cycles. Are you gonna keep working on GraphPack? Or I can push through

**Comment by tmoreau89** [comment]
@MarisaKirisame I had to put the work on hold; if you have free cycles, please re-open the PR, and ensure it doesn't break the unit tests. We'll eventually need to refactor graph pack along with quantization into a pass that is more generic and less VTA specific. For now it will help to be able to label subgraph as offloadable to VTA / other accelerators.

**Pull request closed without merging**
