### PR TITLE
[Relay] [Error] fuse does not work on trivial usecase of tuplegetitem

### PR DESCRIPTION
**Pull request by MarisaKirisame**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
@masahi @tqchen @vinx13 do you three has any idea how to fix this?

**Comment by masahi** [comment]
I'll take a look.

**Comment by masahi** [comment]
@MarisaKirisame For the trivial function below that returns a tuple, infer_type pass generates a redundant function. Is this expected? 
```
func = relay.Function([], relay.Tuple([relay.const(1), relay.const(2)]))
```

Before infer_type
```
%0 = fn () {
  (1, 2)
}
```

After infer_type
```
fn () -> (int32, int32) {
  %0 = fn () -> (int32, int32) {
    (1, 2)
  }
  %0() /* ty=(int32, int32) */
}
```

**Comment by masahi** [comment]
@MarisaKirisame Here is the IR of your test case after fusion. The inner most function is inserted by fusion pass. The second function seems to be inserted by infer type pass and it is redundant.

```
fn () -> int32 {
  %2 = fn () -> int32 {
    %1 = fn (%p0: int32, %p1: int32, __dict__=meta[StrMap][0]) -> int32 {
      %0 = (%p0, %p1)
      %0.0
    }
    %1(1, 2)
  }
  %2()
}
```

**Comment by masahi** [comment]
@MarisaKirisame ok, the cause was [this line](https://github.com/dmlc/tvm/blob/master/src/relay/pass/fuse_ops.cc#L870). Currently, when we make a new subfusion in the fusion pass, the fused function is always "Primitive" function. For this test case, if you replace that line with  
```
func = FunctionSetAttr(func, "Primitive", tvm::Integer(0));
```
it will work. Now the question is how to decide if the new fused function should be primitive or not.

**Comment by tqchen** [comment]
@MarisaKirisame it is better to continue the discussion with a new thread on https://discuss.tvm.ai/ with a development tag

**Pull request closed without merging**
