### PR TITLE
[Bugfix][caffe2] Fix caffe2 relay frontend

### PR DESCRIPTION
**Pull request by hlu1**
Fixed a few bugs in the caffe2 relay frontend.

### CODE REVIEW

**Comment by jroesch** [comment]
Is it possible to add a test for this case?

**Comment by tqchen** [comment]
ping @hlu1 can you act based on comments?

**Comment by hlu1** [comment]
Added test cases for elementwise Add (with and without broadcast) and NormalizePlanarYUV

**Comment by tqchen** [comment]
Thanks @hlu1 , this is now merged

**Pull request merged**
