### PR TITLE
Expose llvm.nearbyint intrinsic. This is a faster alternate to rounding.

### PR DESCRIPTION
**Pull request by kimishpatel**
In the quantized gemm implementation we are working on, we need to quantize input data. During this step we first apply scale and zero point to the input data. Then we do rounding and casting to int8.

`tvm::round` gets lowered by llvm into `roundf` function call which make the op slower. I instead exposed `llvm.nearbyint` via tvm and was able to recover the lost performance.

So this PR is just upstreaming that change.

### CODE REVIEW

**Comment by kimishpatel** [comment]
@tqchen, sorry have to tag you again on this PR as it seems that you may be the right person. Please feel free to suggest anyone else, but this is a quite small PR.

**Comment by tqchen** [comment]
As per https://docs.tvm.ai/contribute/code_review.html#ensure-test-coverage

Thanks @kimishpatel

**Comment by kimishpatel** [comment]
Thanks @tqchen, I have added test case and python binding. Thanks for your feedback.

**Comment by anijain2305** [comment]
@kimishpatel Thanks for the PR. You can also look at qnn.op.quantize. this is a wrapper that internally lowers to the sequence of relay ops you mentioned. This PR will benefit that wrapper as wrll

**Comment by kimishpatel** [comment]
@anijain2305, thanks for the pointer. Wasn't quite aware of that.

**Comment by anijain2305** [comment]
> @anijain2305, thanks for the pointer. Wasn't quite aware of that.

If you are looking at running pre quantized models, you might want to have a look at QNN dialect. We have added a number of QNN ops in there that deal with scale and zero points.

**Comment by kimishpatel** [comment]
@tqchen, sorry to bug again :). Seems like all checks have passed, so just nudging for the merge. Thanks a bunch.

**Comment by tqchen** [comment]
Thanks @anijain2305 @kimishpatel

**Pull request merged**
