### PR TITLE
[TVM] [NNPACK] Modernize and improve NNPACK bindings

### PR DESCRIPTION
**Pull request by ajtulloch**
Despite our best efforts, we still see substantially slower performance
in for certain 3x3 layers on ARMv7 with TVM implementations (direct,
Winograd F(2x2, 3x3), F(4x4, 3x3), F(6x6, 3x3)) compared to a
well-configured NNPACK's F(6x6, 3x3) with FP16 storage. There are
several candidate solutions to this (tensorizing the batch gemm with
custom layouts closes the gap in several cases), but I haven't found a
strictly superior implementation.

This PR updates the existing NNPACK implementation in several ways:

- Updates the NNPack.cmake file to build against current NNPACK (which
has several new dependencies, such as [cpuinfo](https://github.com/pytorch/cpuinfo/)).
- Implements support for pre-transformed weights in the NNPACK bindings,
which is crucial for optimal performance in several layers. A subsequent
PR (already available in e.g.
https://github.com/ajtulloch/tvm/tree/nnpack-precompute-ARM) exposes
this to `AlterOpLayout` to allow precomputation of weight transforms in
the `PrecomputePrune` stage.
- Improves the threadpool configuration to correctly set a null
`pthreadpool` instances in the `num_threads == 1` case, which allows the
calls to be executed directly on the calling thread as desired.
- Improves the `nnpack.convolution_inference` wrapper to support passing
a batch of inputs, which in some cases provides superior performance to
invoking `nnpack.convolution_output`.
- Supports `nnpack.convolution_inference` with and without a bias.
- Improves unit test coverage for the various new functions described above.

### CODE REVIEW

**Comment by ajtulloch** [comment]
Lint failed due to 

```
C:131, 0: Function name "convolution_inference_without_weight_transform" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)

C:183, 0: Function name "convolution_inference_weight_transform" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
```

being too long (38 characters). Does anyone have suggestions for name changes or should we ignore the lint? I was following the convention from https://github.com/dmlc/tvm/blob/9f441d817c7e3c5eeeb0078c5c60701a6e7ba33b/topi/python/topi/arm_cpu/conv2d.py#L495-L497, etc.

**Comment by ajtulloch** [comment]
Note that the NNPACK bindings here wouldn't have actually compiled for about a year (since https://github.com/Maratyszcza/NNPACK/commit/65d0626b3234aa2e50a439360359dfc5ed642bcd), so I think a good follow up (that I could take) would be adding `set(USE_NNPACK ON)` + `test_nnpack.py` to the CPU CIs.

**Comment by tqchen** [comment]
Thanks, @ajtulloch this is merged.  For CI, we are using a CI image that is relatively stable, please send in update to the CI docker as a separate PR, then I will update the image and we can add the test case.

In the meanwhile, it is still worth to improve the 3x3 ops with tensorizations just as a alternative and see how far we can get through AutoTVM

**Comment by ajtulloch** [comment]
My attempt (not sure how to test without commit access) to the CI Docker/Jenkins updates are in https://github.com/dmlc/tvm/pull/2085.

I agree re: tensorization - we have very promising results on NCHWc + tensorizing the batch gemm, but it's still a WIP to beat NNPACK (let alone WT-FP16 NNPACK) for all configurations.

**Pull request merged**
